<?php
    /* 
    echo $this->headLink(array('rel' => 'stylesheet', 
                                 'href' => $this->basePath() . '/assets/css/jquery-ui.min.css'));

    echo $this->headLink(array('rel' => 'stylesheet', 
                                 'href' => $this->basePath() . '/assets/css/datepicker.css'));

    echo $this->headLink(array('rel' => 'stylesheet', 
                                 'href' => $this->basePath() . '/assets/css/ui.jqgrid.css'));
    */                             
    $this->headLink()
        ->appendStylesheet($this->basePath() . '/assets/css/jquery-ui.min.css')
        ->appendStylesheet($this->basePath() . '/assets/css/datepicker.css')
        ->appendStylesheet($this->basePath() . '/assets/css/ui.jqgrid.css');
  
    $this->headScript()->appendFile( $this->basePath() . '/js/grids.js','text/javascript',array());

?>
