
    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
        <i class="ace-icon fa fa-envelope "></i> <!--icon-animated-vertical-->
        <i class="ace-icon fa fa-caret-down"></i>
    </a>

    <ul class="dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
        <li class="dropdown-header">
            <i class="ace-icon fa fa-envelope-o"></i>
            Emails
        </li>

        <li class="dropdown-content">
            <ul class="dropdown-menu dropdown-navbar">
                <li>
                    <a href="#">
                        <span class="msg-body">
                            <span class="msg-title">
                                <span class="blue">Sabih Nasir:</span>
                                Updates to documents section ...
                            </span>

                            <span class="msg-time">
                                <i class="ace-icon fa fa-clock-o"></i>
                                <span>a moment ago</span>
                            </span>
                        </span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span class="msg-body">
                            <span class="msg-title">
                                <span class="blue">Haroon:</span>
                                Reporting tool support ...
                            </span>

                            <span class="msg-time">
                                <i class="ace-icon fa fa-clock-o"></i>
                                <span>20 minutes ago</span>
                            </span>
                        </span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span class="msg-body">
                            <span class="msg-title">
                                <span class="blue">Sabih Nasir:</span>
                                Reporting dead line is changed ...
                            </span>

                            <span class="msg-time">
                                <i class="ace-icon fa fa-clock-o"></i>
                                <span>3:15 pm</span>
                            </span>
                        </span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span class="msg-body">
                            <span class="msg-title">
                                <span class="blue">Mubariz Warryach:</span>
                                Aamila meeting on Sunday ...
                            </span>

                            <span class="msg-time">
                                <i class="ace-icon fa fa-clock-o"></i>
                                <span>1:33 pm</span>
                            </span>
                        </span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span class="msg-body">
                            <span class="msg-title">
                                <span class="blue">Khalid Saeed:</span>
                                Please submit your report  ...
                            </span>

                            <span class="msg-time">
                                <i class="ace-icon fa fa-clock-o"></i>
                                <span>10:09 am</span>
                            </span>
                        </span>
                    </a>
                </li>
            </ul>
        </li>

        <li class="dropdown-footer">
            <a href="#page/home/ajax/inbox.html">
                See all messages
                <i class="ace-icon fa fa-arrow-right"></i>
            </a>
        </li>
    </ul>
