        
        <?php foreach ($this->container as $page) { ?>
            <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
            <?php // when using partials we need to manually check for ACL conditions ?>
            <?php // if (!$page->isVisible() || !$this->navigation()->accept($page)) { continue; } ?>

            <?php if (! $this->navPlus()->haveAccess($page) ){ continue; } ?>
            
			<?php
				$activePage='';$openPage='';
				if($this->navPlus()->isActive($page)){
				     $activePage="active";
				     $openPage='open'; 
                } 
			?>
            
            <?php $hasChildren = $page->hasPages(); ?>
            <?php $customProperties=$page->getCustomProperties() ?>
            <?php if (!$hasChildren) { ?>
                <li class="<?php echo $activePage;?> hover">
                    <a href="<?php echo $page->getHref() ?>" >
                        <?php echo $customProperties['icon'] ?>
                        <span class="menu-text">
                        <?php echo $this->translate($page->getLabel()) ?>
                        </span>
                    </a>
                </li>
            <?php } else { ?>
              <li class="<?=$openPage;?> <?=$activePage;?> hover">
                <!--<a href="#" class="dropdown-toggle ">-->
                    <a href="<?php echo $page->getHref() ?>" class="">
                    <?php echo $customProperties['icon'] ?>
                    <span class="menu-text">
                       <?php echo $this->translate($page->getLabel()) ?>
                    </span>
                    <b class="arrow fa fa-angle-down"></b>
                    </a>
                <!--</a>-->

                <b class="arrow"></b>
                <ul class="submenu ">

                    <?php foreach ($page->getPages() as $child) { ?>
                        <?php // when using partials we need to manually check for ACL conditions 
                             //TODO hide navigation if not allowed
                             //if(!$child->isVisible() || !$this->navigation()->accept($child)) { continue; }
                        ?>
                        <?php if (! $this->navPlus()->haveAccess($child) ){ continue; } ?>
						<?php
							$activeChild='';
							if($this->navPlus()->isActive($child)){ $activeChild="active"; } 
						?>
                        <li class="<?php echo $activeChild;?>">
                            <a data-url="<?php echo $child->getHref() ?>" href="<?php echo $child->getHref() ?>">
                                <i class="menu-icon fa fa-caret-right"></i>
                                <?php $childCustProps=$child->getCustomProperties() ?>
                                <span style="padding-left: 10px">
                                <?php echo (key_exists('icon',$childCustProps)?$childCustProps['icon']:''); ?>
                                <?php echo $this->translate($child->getLabel()) ?>
                                </span>
                            </a>
                           <b class="arrow"></b>
                        </li>
                    <?php } ?>
                </ul>
            </li>
            <?php } ?>
        <?php } ?>