<ul class=" nav nav-list">
<li class="hover">
    <a href="#" class="dropdown-toggle ">
        <i class="menu-icon fa fa-cog bigger-150"></i>
        <span class="menu-text">Settings</span>
        <b class="arrow fa fa-angle-down"></b>
    </a>
    <b class="arrow"></b>
    <ul class="submenu ">
        <li>
            <div class="ace-settings-item2" style="padding-bottom: 2px;">
                <div class="pull-left">
                    <select id="skin-colorpicker" class="hide">
                        <option data-skin="no-skin" value="#438EB9">#438EB9</option>
                        <option data-skin="skin-1" value="#222A2D">#222A2D</option>
                        <option data-skin="skin-2" value="#C6487E">#C6487E</option>
                        <option data-skin="skin-3" value="#D0D0D0">#D0D0D0</option>
                    </select>
                </div>
                <span>&nbsp; Choose Skin</span>
            </div>
           </li>
           <li>

                    <div class="ace-settings-item2">
                        <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-navbar" />
                        <label class="lbl" for="ace-settings-navbar"> Fixed Navbar</label>
                    </div>
           </li>
           <li>

                    <div class="ace-settings-item2">
                        <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-sidebar" />
                        <label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
                    </div>

           </li>
           <li>

                    <div class="ace-settings-item2">
                        <input type="checkbox" class="ace ace-checkbox-2" checked="true" id="ace-settings-add-container" />
                        <label class="lbl" for="ace-settings-add-container">
                            Center Page / Full Screen
                        </label>
                    </div>
           </li>
           <li>

                    <div class="ace-settings-item2">
                        <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-hover" />
                        <label class="lbl" for="ace-settings-hover"> Submenu on Hover</label>
                    </div>
           </li>
           <li>

                    <div class="ace-settings-item2">
                        <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-compact" />
                        <label class="lbl" for="ace-settings-compact"> Compact Sidebar</label>
                    </div>
           </li>
           <li>

                    <div class="ace-settings-item2">
                        <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-highlight" />
                        <label class="lbl" for="ace-settings-highlight"> Alt. Active Item</label>
                    </div>
           </li>
        </ul>
    </li>
</ul>