        <li class="" style="vertical-align: bottom!important">
	        <style>
	            .btn-text-size{
	                background-color:none!important;        
	                padding-left:5px!important;
	                padding-right:5px!important;
	                vertical-align: bottom!important;
	                border-left: solid 1px blue;
	                border-width: 1px!important;
	            }
	            .text-size-1{
	                padding-top:22px;
	                height:45px;
	                font-size:100%;
	            }
	            .text-size-2{
	                padding-top:16px;
	                height:45px;
	                font-size:140%;
	            }
	            .text-size-3{
	                padding-top:12px;
	                height:45px;
	                font-size:160%;
	            }
	            .btn-text-size.btn.btn-white.active, .btn-text-size.btn.btn-white:focus{
	                box-shadow:none!important;
	                height:45px;
	            }
	            
	        </style>
            <div data-toggle="buttons" class="btn-group btn-overlap  " style="vertical-align: bottom!important">
                <label class="btn active btn-white  btn-primary  btn-text-size text-size-1" data-zoom="no-zoom">
                    <input type="radio" value="no-zoom">A
                </label>

                <label class="btn btn-primary btn-text-size text-size-2"  data-zoom="zoom-115">
                    <input type="radio" value="zoom-115">A
                </label>

                <label class="btn  btn-primary  btn-text-size text-size-3"  data-zoom="zoom-125">
                    <input type="radio" value="zoom-125">A
                </label>
            </div>
            <script>
                $(function(){
                    $('.btn-text-size').on('click',function(){ 
                        $('.btn-text-size').removeClass('btn-white');
                        $(this).addClass('btn-white');

                        var value=$(this).find('input').val();
                        
                        if( ! $('body').hasClass(value)){
                            $('body').removeClass('no-zoom zoom-115 zoom-125');
                            $('body').addClass(value);
                            var data = {};
                            data['zoom']=value;
                            $.post( "<?=$this->url('user-profile/settings')?>", data);
                        }
                        
                        // $('body').removeClass('bigger-140');
                        // $('body').removeClass('bigger-160');
                        // var fclass=('bigger-'+(value*2*10+100));                        
                        // if(value>0){
                            // if(fclass!=''){
                            // }
                        // }
                     });
                });
                
            </script>
        </li>


        <?php foreach ($this->container as $page) { ?>
            <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
            <?php // when using partials we need to manually check for ACL conditions ?>
            <?php // if (!$page->isVisible() || !$this->navigation()->accept($page)) { continue; } ?>

            <?php if ( ! $this->navPlus()->haveAccess($page) ){ continue; } ?>
            
			<?php
				$activePage='';
				if($this->navPlus()->isActive($page)){
				     $activePage="active"; 
                } 
			?>
            
            <?php $hasChildren = $page->hasPages(); ?>
            <?php $customProperties=$page->getCustomProperties() ?>
            <?php if (key_exists('detailed', $customProperties)){ continue; } //only display on detailed menu?>        
              <li class="<?=$customProperties['addclass']?>" id="top_nav_<?=$page->getLabel()?>">
                <a  href="<?php echo $page->getHref() ?>" class="dropdown-toggle bigger-160">
                    <?php echo $customProperties['icon'] ?>
                    <!--
                    <span class="menu-text">
                       <?php echo $this->translate($page->getLabel()) ?>
                    </span>
                   -->
                </a>

            </li>
        <?php } ?>


<!--
        <li class="grey">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <i class="ace-icon fa fa-tasks"></i>
                <span class="badge badge-grey">4</span>
            </a>

            <ul class="dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
                <li class="dropdown-header">
                    <i class="ace-icon fa fa-check"></i>
                    4 Tasks to complete
                </li>

                <li>
                    <a href="#">
                        <div class="clearfix">
                            <span class="pull-left">Software Update</span>
                            <span class="pull-right">65%</span>
                        </div>

                        <div class="progress progress-mini">
                            <div style="width:65%" class="progress-bar"></div>
                        </div>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <div class="clearfix">
                            <span class="pull-left">Hardware Upgrade</span>
                            <span class="pull-right">35%</span>
                        </div>

                        <div class="progress progress-mini">
                            <div style="width:35%" class="progress-bar progress-bar-danger"></div>
                        </div>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <div class="clearfix">
                            <span class="pull-left">Unit Testing</span>
                            <span class="pull-right">15%</span>
                        </div>

                        <div class="progress progress-mini">
                            <div style="width:15%" class="progress-bar progress-bar-warning"></div>
                        </div>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <div class="clearfix">
                            <span class="pull-left">Bug Fixes</span>
                            <span class="pull-right">90%</span>
                        </div>

                        <div class="progress progress-mini progress-striped active">
                            <div style="width:90%" class="progress-bar progress-bar-success"></div>
                        </div>
                    </a>
                </li>

                <li class="dropdown-footer">
                    <a href="#">
                        See tasks with details
                        <i class="ace-icon fa fa-arrow-right"></i>
                    </a>
                </li>
            </ul>
        </li>

        <li class="purple">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <i class="ace-icon fa fa-bell icon-animated-bell"></i>
                <span class="badge badge-important">8</span>
            </a>

            <ul class="dropdown-menu-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close">
                <li class="dropdown-header">
                    <i class="ace-icon fa fa-exclamation-triangle"></i>
                    8 Notifications
                </li>

                <li>
                    <a href="#">
                        <div class="clearfix">
                            <span class="pull-left">
                                <i class="btn btn-xs no-hover btn-pink fa fa-comment"></i>
                                New Comments
                            </span>
                            <span class="pull-right badge badge-info">+12</span>
                        </div>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <i class="btn btn-xs btn-primary fa fa-user"></i>
                        Bob just signed up as an editor ...
                    </a>
                </li>

                <li>
                    <a href="#">
                        <div class="clearfix">
                            <span class="pull-left">
                                <i class="btn btn-xs no-hover btn-success fa fa-shopping-cart"></i>
                                New Orders
                            </span>
                            <span class="pull-right badge badge-success">+8</span>
                        </div>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <div class="clearfix">
                            <span class="pull-left">
                                <i class="btn btn-xs no-hover btn-info fa fa-twitter"></i>
                                Followers
                            </span>
                            <span class="pull-right badge badge-info">+11</span>
                        </div>
                    </a>
                </li>

                <li class="dropdown-footer">
                    <a href="#">
                        See all notifications
                        <i class="ace-icon fa fa-arrow-right"></i>
                    </a>
                </li>
            </ul>
        </li>

        <li class="green">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <i class="ace-icon fa fa-envelope icon-animated-vertical"></i>
                <span class="badge badge-success">5</span>
            </a>

            <ul class="dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
                <li class="dropdown-header">
                    <i class="ace-icon fa fa-envelope-o"></i>
                    5 Messages
                </li>

                <li class="dropdown-content">
                    <ul class="dropdown-menu dropdown-navbar">
                        <li>
                            <a href="#">
                                <img src="../assets/avatars/avatar.png" class="msg-photo" alt="Alex's Avatar" />
                                <span class="msg-body">
                                    <span class="msg-title">
                                        <span class="blue">Alex:</span>
                                        Ciao sociis natoque penatibus et auctor ...
                                    </span>

                                    <span class="msg-time">
                                        <i class="ace-icon fa fa-clock-o"></i>
                                        <span>a moment ago</span>
                                    </span>
                                </span>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <img src="../assets/avatars/avatar3.png" class="msg-photo" alt="Susan's Avatar" />
                                <span class="msg-body">
                                    <span class="msg-title">
                                        <span class="blue">Susan:</span>
                                        Vestibulum id ligula porta felis euismod ...
                                    </span>

                                    <span class="msg-time">
                                        <i class="ace-icon fa fa-clock-o"></i>
                                        <span>20 minutes ago</span>
                                    </span>
                                </span>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <img src="../assets/avatars/avatar4.png" class="msg-photo" alt="Bob's Avatar" />
                                <span class="msg-body">
                                    <span class="msg-title">
                                        <span class="blue">Bob:</span>
                                        Nullam quis risus eget urna mollis ornare ...
                                    </span>

                                    <span class="msg-time">
                                        <i class="ace-icon fa fa-clock-o"></i>
                                        <span>3:15 pm</span>
                                    </span>
                                </span>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <img src="../assets/avatars/avatar2.png" class="msg-photo" alt="Kate's Avatar" />
                                <span class="msg-body">
                                    <span class="msg-title">
                                        <span class="blue">Kate:</span>
                                        Ciao sociis natoque eget urna mollis ornare ...
                                    </span>

                                    <span class="msg-time">
                                        <i class="ace-icon fa fa-clock-o"></i>
                                        <span>1:33 pm</span>
                                    </span>
                                </span>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <img src="../assets/avatars/avatar5.png" class="msg-photo" alt="Fred's Avatar" />
                                <span class="msg-body">
                                    <span class="msg-title">
                                        <span class="blue">Fred:</span>
                                        Vestibulum id penatibus et auctor  ...
                                    </span>

                                    <span class="msg-time">
                                        <i class="ace-icon fa fa-clock-o"></i>
                                        <span>10:09 am</span>
                                    </span>
                                </span>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="dropdown-footer">
                    <a href="inbox.html">
                        See all messages
                        <i class="ace-icon fa fa-arrow-right"></i>
                    </a>
                </li>
            </ul>
        </li>
-->
        <!-- #section:basics/navbar.user_menu -->
        <!-- User inforation -->
<?php if($this->zfcUserIdentity()): ?>
        <li class="grey">
            <a data-toggle="dropdown" href="#" class="dropdown-toggle ">
                <i class="ace-icon fa fa-user bigger-160 align-middle"></i>
                    <!-- display the 'display name' of the user -->
                    <!--
                <span class="user-info">
                    <small>Assalamu Alaikum,</small>
                    <?php echo $this->zfcUserIdentity()->getDisplayname(); ?>
                </span>
                <i class="ace-icon fa fa-caret-down"></i>
                    -->
            </a>

            <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">

                <li>
                    <a>
                        <span class="user-info">
                            <small>Assalamu Alaikum,</small>                            
                        </span>
                    </a>
                </li>

                <li>
                    <a>
                        <span class="user-info">
                            <?php echo $this->zfcUserIdentity()->getDisplayname(); ?>
                        </span>
                    </a>
                </li>

                <li class="divider"></li>

                <li>
                    <a href="<?=$this->url('user-profile')?>">
                        <i class="ace-icon fa fa-user"></i>
                        Profile
                    </a>
                    <!-- add messages -->
                    
                    <?php if($this->messages()->outstandingCount() > 0):?>
                    <script>
                        $(function(){
                            $('#top_nav_Messages > a').append('<span class="badge badge-important"><?=$this->messages()->outstandingCount()?></span>');
                            $('#top_nav_Messages > a > i').addClass('icon-animated-vertical');
                        });                        
                    </script>
                    <?php endif?>
                </li>

                <li class="divider"></li>

                <li>
                    <a href="<?php echo $this->url('auth/logout'); ?>">
                        <i class="ace-icon fa fa-power-off"></i>
                        Logout
                    </a>
                </li>
            </ul>
        </li>
        
        <li class="orange2 orange red ">
              <a class="" href="<?=$this->url('home/help'); ?>">        
                <i class=" ace-icon glyphicon glyphicon-question-sign bigger-150 align-middle"></i>
                &nbsp;
                Help 
                &nbsp;
            </a>
            <!-- help -->
            <!--
                <a href="<?=$this->url('home/help'); ?>" data-tooltip="Help" title="Help" data-original-title="Help" class=" align-middle success no-padding" style="padding-top: 16px;">
                    <span class="glyphicon glyphicon-question-sign middle" style="font-size: 20pt;"></span>
                 </a>
            -->
        </li>
<?php else:?>    
        <li class="light-blue">
            <a href="#" class="">
                <i class="ace-icon fa fa-key"></i>
                <span class="">
                    <!-- display the 'display name' of the user -->
                    Login
                </span>
            </a>
        </li>
<?php endif?>
