                            
                            <div class="message-container">
                                <!-- #section:pages/inbox.navbar -->
                                <div id="id-message-list-navbar" class="message-navbar clearfix">
                                    <div class="message-bar">
                                        <div class="message-infobar" id="id-message-infobar">
                                            <span class="blue bigger-150">Inbox</span>
                                            <?php if (count($this->messages()->unread())>0):?>
                                            <span class="grey bigger-110">(<?=count($this->messages()->unread())?> unread messages)</span>
                                            <?php endif?>
                                        </div>

                                        <div class="message-toolbar hide">
					  
					<!--
                                           <button type="button" class="btn btn-xs btn-white btn-primary  bigger-110 btn-round">
                                                <i class="ace-icon fa fa-mail-reply blue"></i>&nbsp; Reply
                                            </button>                        
                                         -->  

                                            <button type="button" class="btn btn-xs btn-white btn-primary">
                                                <i class="ace-icon fa fa-trash-o bigger-125 orange"></i>
                                                <span class="bigger-110">Delete</span>
                                            </button>

					<!--

                                          <button type="button" class="btn btn-xs btn-white btn-primary  bigger-110 btn-round">
                                                <i class="ace-icon fa fa-folder-open orange"></i>&nbsp; Archive
                                            </button>
                                            <button type="button" class="btn btn-xs btn-white btn-primary  bigger-110 btn-round">
                                                    <i class="ace-icon fa fa-eye blue"></i>&nbsp; Mark as read
                                            </button>
                                            <button type="button" class="btn btn-xs btn-white btn-primary bigger-110 btn-round">
                                                <i class="ace-icon fa fa-eye-slash green"></i>&nbsp; Mark unread
                                            </button>
                                            
                                            <button type="button" class="btn btn-xs btn-white btn-primary">
                                                <i class="ace-icon fa fa-trash-o bigger-125 orange"></i>
                                                <span class="bigger-110">Delete</span>
                                            </button>
                                            -->
                                        </div>
                                    </div>

                                    <div>
                                        <div class="messagebar-item-left">
                                            <label class="inline middle">
                                                <input type="checkbox" id="id-toggle-all" class="ace" />
                                                <span class="lbl"></span>
                                            </label>

                                            &nbsp;
                                            <div class="inline position-relative">
                                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                                                    <i class="ace-icon fa fa-caret-down bigger-125 middle"></i>
                                                </a>

                                                <ul class="dropdown-menu dropdown-lighter dropdown-100">
                                                    <li>
                                                        <a id="id-select-message-all" href="#">All</a>
                                                    </li>

                                                    <li>
                                                        <a id="id-select-message-none" href="#">None</a>
                                                    </li>

                                                    <li class="divider"></li>

                                                    <li>
                                                        <a id="id-select-message-unread" href="#">Unread</a>
                                                    </li>

                                                    <li>
                                                        <a id="id-select-message-read" href="#">Read</a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>

                                        <div class="messagebar-item-right">
                                            <div class="inline position-relative">
                                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                                                    Sort &nbsp;
                                                    <i class="ace-icon fa fa-caret-down bigger-125"></i>
                                                </a>

                                                <ul class="dropdown-menu dropdown-lighter dropdown-menu-right dropdown-100">
                                                    <li>
                                                        <a href="#">
                                                            <i class="ace-icon fa fa-check green"></i>
                                                            Date
                                                        </a>
                                                    </li>

                                                    <li>
                                                        <a href="#">
                                                            <i class="ace-icon fa fa-check invisible"></i>
                                                            From
                                                        </a>
                                                    </li>

                                                    <li>
                                                        <a href="#">
                                                            <i class="ace-icon fa fa-check invisible"></i>
                                                            Subject
                                                        </a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>

                                        <!-- #section:pages/inbox.navbar-search -->
                                        <div class="nav-search minimized">
                                            <!--
                                            <form class="form-search">
                                                <span class="input-icon">
                                                    <input type="text" autocomplete="off" class="input-small nav-search-input" placeholder="Search inbox ..." />
                                                    <i class="ace-icon fa fa-search nav-search-icon"></i>
                                                </span>
                                            </form>
                                            -->
                                        </div>

                                        <!-- /section:pages/inbox.navbar-search -->
                                    </div>
                                </div>

                                <!-- # Message-Item-Details-Bar-Start -->
                                <div id="id-message-item-navbar" class="hide message-navbar clearfix">
                                    <div class="message-bar">
                                        <div class="message-toolbar">
                                            <div class="inline position-relative align-left">
                                            <button type="button" class="btn btn-xs btn-white btn-primary">
                                                <i class="ace-icon fa fa-trash-o bigger-125 orange"></i>
                                                <span class="bigger-110">Delete</span>
                                            </button>

					   <!--
                                           <button type="button" class="btn btn-xs btn-white btn-primary  bigger-110 btn-round">
                                                <i class="ace-icon fa fa-mail-reply blue"></i>&nbsp; Reply
                                            </button>                        
                                                         
                                          <button type="button" class="btn btn-xs btn-white btn-primary  bigger-110 btn-round">
                                                <i class="ace-icon fa fa-folder-open orange"></i>&nbsp; Archive
                                            </button>


                                            <button type="button" class="btn btn-xs btn-white btn-primary  bigger-110 btn-round">
                                                    <i class="ace-icon fa fa-eye blue"></i>&nbsp; Mark as read
                                            </button>
                                            <button type="button" class="btn btn-xs btn-white btn-primary bigger-110 btn-round">
                                                <i class="ace-icon fa fa-eye-slash green"></i>&nbsp; Mark unread
                                            </button>
					-->
                                            </div>
                                        </div>
                                    </div>

                                    <div>
                                        <div class="messagebar-item-left">
                                            <a href="#" class="btn-back-message-list" id"btn-back-message-list-id">
                                                <i class="ace-icon fa fa-arrow-left blue bigger-110 middle"></i>
                                                <b class="bigger-110 middle">Back</b>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <!-- # / Message-Item-Details-Bar-End -->

                                <!-- /section:pages/inbox.navbar -->
                                <div class="message-list-container">
                                    <!-- #section:pages/inbox.message-list -->
                                    <div class="message-list" id="message-list-inbox">
                                        
                                        <?php
                                        
                                            $messages = $this->messages;
                                                                    
                                            $this->partialLoop()->setObjectKey('message');
                                            
                                            echo $this->partialLoop('messages/mailbox_list', $this->messages()->inbox());
                                            
                                        ?>
                                        
                                    </div>

                                    <!-- /section:pages/inbox.message-list -->
                                </div>

                                <!-- #section:pages/inbox.message-footer -->
                                <div class="message-footer clearfix ">
                                    <div class="pull-left"> <?=count($this->messages()->inbox())?> messages total </div>

                                    <div class="pull-right">
                                        <div class="inline middle"> page 1 of 1 </div>

                                        &nbsp; &nbsp;
                                        <ul class="pagination middle">
                                            <li class="disabled">
                                                <span>
                                                    <i class="ace-icon fa fa-step-backward middle"></i>
                                                </span>
                                            </li>

                                            <li class="disabled">
                                                <span>
                                                    <i class="ace-icon fa fa-caret-left bigger-140 middle"></i>
                                                </span>
                                            </li>

                                            <li>
                                                <span>
                                                    <input value="1" maxlength="3" type="text" />
                                                </span>
                                            </li>

                                            <li>
                                                <a href="#">
                                                    <i class="ace-icon fa fa-caret-right bigger-140 middle"></i>
                                                </a>
                                            </li>

                                            <li>
                                                <a href="#">
                                                    <i class="ace-icon fa fa-step-forward middle"></i>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <!-- /section:pages/inbox.message-footer -->


                            </div><!-- / Inbox messageContainer -->
                            
