

<div class="col-md-6 col-xs-12 no-padding no-margin panel panel-default widget-container-col no-padding">

	<form class="form-horizontal" role="form" id="requestOfficeAssignmentForm" method="post" action="<?php echo $this->url("office-assignment/new-request") ?>"  

<div class="no-margin no-padding widget-box no-border" id="user_info_widget_box">
    <div class="widget-header widget-header-small  ">
        <h5 class="widget-title smaller"><?php echo $this->translate('Create Report') ?></h5>
        <div class="widget-toolbar">
			<a href="#" data-action="collapse">
				<i class="ace-icon fa fa-chevron-up"></i>
			</a>
		</div>
    </div>
    <div class="widget-body widget-main no-margin no-padding">    

		<div class="space-10"></div>
    	<div class="form-container">
           <div class="form-group">
              <label class="col-sm-4 control-label no-padding-right" for="full_name">Full Name</label>
              <div class="col-sm-7">
                <input type="text" class="form-control input-xlarge" placeholder=" of the office bearer" id="full_name" name="full_name"  required="true" value=""></input>
              </div>
           </div>
    	</div>
    	
	    <div class="widget-toolbox clearfix margin padding-6 align-center">    			
			
			<button class="btn btn-sm btn-round btn-primary ">Save&nbsp;&nbsp;<i class="fa fa-save"></i>&nbsp;
			</button>
			&nbsp;&nbsp;
			<button class="btn btn-success btn-sm btn-round ">
				Submit
				<i class="fa  fa-check-square-o "></i>
			</button>
	    	
	    </div>
    </div>
        
</div>

</form>

</div>
