<style>
    .r_title {text-align: center; font-size: 18px;}
    .r_row {border-bottom: 1px solid #a29a9a;     background-color: #f1f1f1;}
    .r_sub_row {border-bottom: 1px solid #d2cdcd}
    .r_month {padding-left: 50px}
    .r_sno {min-width:20px}
</style>

<table>
    <tr class="r_row">
        <th colspan="4" class="r_title">Summary Report</th>
    </tr>
    <?php 
        $count = 1;
        foreach($this->reportData['data'] as $question) { 
            if( in_array($question['action'], ['sum', 'countif', 'ifempty', 'ifnotempty', 'sumOfLastAnswerOfEach']) ) { ?>
                <tr class="r_row">
                    <td class="r_sno"><?=($count++)?></td>
                    <td class="r_dep"><?=$question['department']?></td>
                    <td colspan="2"><?=$question['caption']?></td>
                    <td><?=$question['data']?></td>
                </tr> <?php
            }
            else if( in_array($question['action'], ['list','listLastAnswerOfEach'] )) {  ?>
                <tr class="r_row">
                    <td class="r_sno"><?=($count++)?></td>
                    <td class="r_dep"><?=$question['department']?></td>
                    <td colspan="3"><?=$question['caption']?></td>
                </tr>            
        <?php   foreach($question['data'] as $data) { ?>
                    <tr class="r_sub_row">
                        <td class="r_sno">&nbsp;</td>
                        <td class="r_dep"><?=$question['department']?></td>
                        <td width="20%" class="r_month"><?=$data['month']?></td>
                        <td width="20%"><?=$data['branch']?></td>
                        <td><?=$data['value']?></td>
                    </tr>
        <?php   } ?>
<?php       } ?>
<?php   } ?>
</table>