<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

<script src='https://code.jquery.com/jquery-3.5.1.js'></script>
<script src='https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js'></script>
<script src='https://cdn.datatables.net/rowreorder/1.2.7/js/dataTables.rowReorder.min.js'></script>

<link rel="stylesheet" href='https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css' />
<link rel="stylesheet" href='https://cdn.datatables.net/rowreorder/1.2.7/css/rowReorder.dataTables.min.css' />

<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.bundle.min.js"></script>
<link rel="stylesheet" href='/ace_admin/assets/css/bootstrap-tagsinput.css' />
<script src="/ace_admin/assets/js/bootstrap-tagsinput.js"></script>

<style>
.report_generator {
    border: 0px
}
</style>

<div class="panel panel-default report_generator">
  <div class="panel-heading">Summary Reports</div>
  <div class="panel-body">
    <form method="post" target="blank">
        <div class="row">
            <div class="col-12 col-md-6">
                <label for="question_action">Title</label>
                <input type="text" value="" class="form-control" id="report_title" name="report_title" />
            </div>
            <div class="col-12 col-md-6">
                    <div class="form-group ">
                        <label for="question_action">&nbsp;</label><br />
                        <input type="submit" id="report_btn" value="Add New Report" /> <a href="#" style="display:none" id="add_report_cancel">Cancel</a>
                    </div>
            </div>
        </div>        
        <input type="hidden" name="report_id" id="report_id" value=""/>
    </form>
   </div>
</div>

<form id="delete_form" method="post" target="blank">
<input type="hidden" name="report_id_delete" id="report_id_delete" value=""/>
</form>

<div class="panel panel-default report_generator">


    <table id="example" class="display" style="width:100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <?php foreach($this->reportData as $data) { ?>
            <tr>
                <td><?=$data->getId()?></td>
                <td><a href="/report/summary?id=<?=$data->getId()?>"><?=$data->getTitle()?></td>
                <td>&nbsp;</td>
            </tr>
        <?php } ?>
        <tfoot>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>&nbsp;</th>
            </tr>
        </tfoot>
    </table>

</div>    
            <br /><br /><br /><br /><br />

<script>
$(document).ready(function() {


    var table = $('#example').DataTable( {
        rowReorder: { update: true, dataSrc: 7 },
        "pageLength": 100,
        "ordering": false,
        "columnDefs": [ {
            "targets": -1,
            "data": null,
            "defaultContent": "<i class=\"fa fa-edit dt_edit\"> &nbsp;&nbsp; </i><i class=\"fa fa-remove dt_delete\"></i>"
        } ]        
    } );

    $('#example tbody').on( 'click', '.dt_edit', function (e) {
        var data = table.row($(e.target).parents('tr')).data();
        $('#report_id').val(data[0]);
        $('#report_title').val($(data[1]).html());
        $('#report_btn').val('Edit Report');
        $('#add_report_cancel').show()
    });

    $('.report_generator').on( 'click', '#add_report_cancel', function (e) {
        e.preventDefault();
        $('#report_id').val('');
        $('#report_title').val('');
        $('#report_btn').val('Add New Report');
        $('#add_report_cancel').hide()
    });

    $('#example tbody').on( 'click', '.dt_delete', function (e) {
        var data = table.row($(e.target).parents('tr')).data();
        if( window.confirm('Are you sure, you want to delete this report and related question.') ) {
            $('#report_id_delete').val(data[0]);
            $( "#delete_form" ).submit();
        }
    });


            
} );
</script>