<?php
    
    $user_msg = $this->user_message;
    $message=null;
    if($user_msg){
        $is_unread = $user_msg->isUnread();   
        $unread_class='';
        $unread_star='';
        if($is_unread){
            $unread_class='message-unread';
            $unread_star='<i class="message-star ace-icon fa fa-star orange2"></i>';
        } 
        
        $message=$user_msg->getMessage();
        echo "[Message via user_message]\n";
    }elseif($this->message){
        $message=$this->message;
        echo "[Message via message]\n";
    }
    
    if( $message != null ){
        $msg_time = $this->smart_format($message->getDateSent(),true);
        $msg_subject = $message->getSubject();
        $msg_html_body = $message->getHtmlBody();
        $msg_text_body = $message->getTextBody();
        $msg_sender = $message->getSentAs();
        $attachments = $message->getAttachments(); 
        
    }else{
        $msg_time='';
        $msg_subject ='';
        $msg_html_body ='';
        $msg_text_body ='';
        $msg_sender ='';
        $attachments =''; 
        
    }
    

?>

<div class="hide message-content" id="id-message-content">
            <!-- #section:pages/inbox.message-header -->
            <div class="message-header clearfix">
                
                <div class="pull-left bigger-110">
                    
                    <a href="#" class="sender" id="message_sender"><?=$msg_sender?></a>
                    &nbsp;
                    <i class="ace-icon fa fa-clock-o bigger-110 orange middle"></i>
                    <span class="time grey" id="mesage_time"><?=$msg_time?></span>

                    <div class="space-4"></div>

                    <div class=" bigger-110" id="message_subject"><?=$msg_subject?></div>
                </div>
            </div>

            <!-- /section:pages/inbox.message-header -->
            <div class="hr hr-double"></div>

            <!-- #section:pages/inbox.message-body -->
            <div class="message-body" id="message_body">
                
                <?php
                
                if(empty($msg_html_body)){
                    echo '<pre>'.$msg_text_body.'</pre>';
                }else{
                    echo $msg_html_body;
                }
                
                ?>
                
            </div>

            <!-- /section:pages/inbox.message-body -->
            <div class="hr hr-double"></div>

            <!-- #section:pages/inbox.message-attachment -->
            <?php 
            if(!empty($attachments)):?>
            <div class="message-attachment clearfix">
                <div class="attachment-title ">
                    <span class="blue bolder bigger-110">Attachments</span>
                    &nbsp;&nbsp;
                    <span class="grey"> <?=count($attachments)?> file(s)</span>
                    <!--
                    <div class="inline position-relative">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                            &nbsp;
                            <i class="ace-icon fa fa-caret-down bigger-125 middle"></i>
                        </a>

                        <ul class="dropdown-menu dropdown-lighter">
                            <li>
                                <a href="#">Download all as zip</a>
                            </li>

                            <li>
                                <a href="#">Display in slideshow</a>
                            </li>
                        </ul>
                    </div>
                    -->
                </div>

                &nbsp;
                <ul class="attachment-list pull-left list-unstyled-not ">
                    <?php foreach ($attachments as $file) :?>
                    <li>
                        <a href="#" class="attached-file">
                            
                            <span class="fa-stack">
                              <span class="fa-stack-2x filetype-text"><?=$file['ext']?></span>
                              <i class="fa fa-file-o fa-stack-2x"></i>
                            </span>
                            <span class="attached-name"><?=$file['name']?></span>
                        </a>

                        <span class="action-buttons">
                            <a title="<?=$file['name']?>" href="<?=$this->url('message/attachment')?>?id=<?=$message->getId()?>&f=<?=$file['saved_as']?>">
                                    
                                <i class="ace-icon fa fa-download bigger-125 blue"></i>
                            </a>
                            <!--
                            <a href="#">
                                <i class="ace-icon fa fa-trash-o bigger-125 red"></i>
                            </a>
                            -->
                        </span>
                    </li>
                   <?php endforeach ?>
                </ul>
                <!--
                <div class="attachment-images pull-right hidden">
                    <div class="vspace-4-sm"></div>

                    <div>
                        <img width="36" alt="image 4" src="../../assets/images/gallery/thumb-4.jpg" />
                        <img width="36" alt="image 3" src="../../assets/images/gallery/thumb-3.jpg" />
                        <img width="36" alt="image 2" src="../../assets/images/gallery/thumb-2.jpg" />
                        <img width="36" alt="image 1" src="../../assets/images/gallery/thumb-1.jpg" />
                    </div>
                </div>
                -->
            </div>
            <?php endif?>
            <!-- /section:pages/inbox.message-attachment -->
        </div><!-- /.message-content -->
