<script src="<?=$this->basePath()?>/assets/js/ckeditor/ckeditor.js"></script>
<script src="<?=$this->basePath()?>/assets/js/ckeditor/adapters/jquery.js"></script>

<?php include __DIR__.'/../../partial/grid_includes.phtml' ?>

<?php

  $report = $this->report; 
    
?>

<form name="question_view_form" id="question_view_form" class="form-horizontal" role="form" target="report_frame"
    enctype="multipart/form-data" method="post" action="<?=$this->url('question-setup/view')?>"
    data-description="Report ">

    <div class="row clearfix">
    <div class="col-sm-12 col-md-12 no-margin no-padding report-panel ">
    <div class="widget-box col-xs-12  col-sm-12 no-border ">

    <div class="col-sm-9 col-xs-12 ">
    <div class="col-sm-12 no-padding  col-xs-12  no-margin bigger-120" >
        <div class="col-sm-12 col-xs-12  no-padding no-margin" >
            <label class="col-sm-2 col-xs-6 input-lable">Department: </label>            
            <div class="col-sm-4 col-xs-6 no-padding no-margin">
                <input class="select2" id="department" name="department"
                value="<?=$this->form->get('department')->getValue()?>" type="text"></input>
             </div>
            <label class="col-sm-2 col-xs-6 input-lable">Branch Name: </label>
            <div class="col-sm-4 col-xs-6 no-padding no-margin">
                <input style="width:350px" class="select2  col-5" id="branch" name="branch"
                value="<?=$this->form->get('branch')->getValue()?>" type="text"></input>
            </div>
        </div>
        <div class="space-6 col-sm-12 col-xs-12 "></div>
        <div class="col-sm-12 col-xs-12  no-padding no-margin" >
            <label class="col-sm-2 col-xs-6 input-lable">Report Month: </label>            
            <div class="col-sm-4 col-xs-6 no-padding no-margin">
            <input style="width:350px" class="select2  col-5" id="period_from" name="period_from"
                            value="<?=$this->form->get('period_from')->getValue()?>" type="text"></input>
             </div>
            <label class="col-sm-2 col-xs-6 input-lable">Report Status: </label>
            <div class="col-sm-4 col-xs-6 no-padding no-margin">
            <input style="width:350px" class="select2  col-5" id="report_status" name="report_status"
                            value="<?=$this->form->get('report_status')->getValue()?>" type="text"></input>
            </div>
        </div>
        <div class="space-6 col-sm-12"></div>        
        <div class="col-sm-12 no-padding no-margin">
            <button type="submit" class=" col-5 btn btn-success btn-white  btn-round btn-sm margin-4 submit-btn"
                value="submit" name="submit">
                <i class="ace-icon fa fa-save"></i>
                <span class="bigger-110">Submit</span>
                <i class="ace-icon fa fa-sign-in icon-on-right"></i>
            </button>
        </div>
    </div>    

    </div><!-- //Widget body -->

    <iframe name="report_frame" style="width:99%;height:800px;margin-left:10px;border: 1px black solid;" src="<?=$this->url('question-setup/empty')?>" ></iframe>

    </div><!-- //Widget box for form -->

    </div>
    </div> <!-- Report section -->

</form>


<div class="space-20"></div>

<script>
function REMOVE_preSaveAction(event) {

}



function createAdvancedFields() {

    //Create Date Pickers
    $('.date-picker').datepicker({
            autoclose: true,
            todayHighlight: false,
            startDate: "2020/06/30",
            endDate: "2020/07/31",
            defaultDate: "<?=date('Y/m/d')?>"
        })
        //show datepicker when clicking on the icon
        .next().css('border', '1px solid #6fb3e0').css('border-top-right-radius', '4px!important').css(
            'border-bottom-right-radius', '4px!important').on(ace.click_event, function() {
            $(this).prev().focus();
        });


    //create ckeditor
    $('.ckeditor').each(function() {
        ReportForms.ckeditor($(this));
    });

    //create rich text editors

    //when adding more answers to a question we need to remove old toolbar
    $('.richtext-div').siblings('.wysiwyg-toolbar').remove();

    $('.richtext-div').ace_wysiwyg({
        height: '100px',
        toolbar: [{
                name: 'font',
                className: 'btn-info btn-round btn-sm btn-white'
            },
            null,
            {
                name: 'fontSize',
                className: 'btn-info btn-round btn-white'
            },
            null,
            {
                name: 'bold',
                className: 'btn-info btn-round btn-white'
            },
            {
                name: 'italic',
                className: 'btn-info btn-round btn-white'
            },
            //{name:'strikethrough', className:'btn-info btn-round btn-white'},
            {
                name: 'underline',
                className: 'btn-info btn-round btn-white'
            },
            null,
            {
                name: 'insertunorderedlist',
                className: 'btn-success btn-round  btn-white'
            },
            {
                name: 'insertorderedlist',
                className: 'btn-success btn-round  btn-white'
            },
            {
                name: 'outdent',
                className: 'btn-purple btn-round btn-white'
            },
            {
                name: 'indent',
                className: 'btn-purple btn-round btn-white'
            },
            null,

            {
                name: 'createLink',
                className: 'btn-pink btn-round btn-white'
            },
            {
                name: 'unlink',
                className: 'btn-pink btn-round btn-white'
            },
            null,
            {
                name: 'insertImage',
                className: 'btn-success btn-round btn-white'
            },
            null,
            {
                name: 'foreColor',
                className: 'btn-round btn-white'
            },
            null,
            {
                name: 'undo',
                className: 'btn-grey btn-round btn-white'
            },
            {
                name: 'redo',
                className: 'btn-grey btn-round btn-white'
            }
        ],
        'wysiwyg': {
            //fileUploadError: showErrorAlert
            hotKeys: {} //disable hotkeys

        }
    }).prev().css('background-color', '#e1e1e1');

    imageResizeForWebkit();

} //createAdvanceFields function



$(function() {

    //create advance controls when layput is not printing
    createAdvancedFields();

    //add collaps action to onclick of yes_no rich text editors
    $('.widget-collapse-switch').each(function() {
        var elem = $(this);
        elem.on('click', function(e) {
            $(this).parent().parent().find('.widget-box-collapse-anchor').click();
        });
    });


    $('.add-more-btn', this).each(function() {
        var btn = $(this);
        btn.on('click', function(e) {

            //stop default propagation of event
            e.preventDefault();

            var question_details_name = btn.data('question-details');
            var details = $('#' + question_details_name + ':last').clone();


            //Change ID of new details container
            var parts = details.attr('id').split('_');
            var count = $('input[id^=Q_' + parts[1] + '_').size() + 1; //
            parts[2] = count;
            details.attr('id', parts.join('_'));

            //remove ckeditor if exists, as we will recreate it
            details.find('textarea').siblings('.cke').remove();

            //Change ID for all children of details
            $(details).find('input,textarea,select,div,span,a,label', this).each(function() {
                var elem = $(this);
                //empty field
                if (elem.val) {
                    elem.val('');
                }
                //empty rich text boxes
                if (elem.hasClass(' richtext-textarea') || elem.hasClass(
                        'richtext-div')) {
                    elem.text('');
                }
                //empty file attachments
                if (elem.find('.files-attached').size() > 0) {
                    elem.find('.files-attached').html('');
                }

                //update id/for if exists
                ['for', 'id', 'name'].forEach(function(attr) {
                    if (elem.attr(attr) && elem.attr(attr).indexOf('_') > 0) {
                        parts = elem.attr(attr).split('_');
                        parts[2] = count; //increment last answer number
                        //console.log(parts.join('_')); 
                        elem.attr(attr, parts.join('_'));
                    }
                });

                if (elem.attr('checked')) {
                    elem.prop('checked', true);
                    elem.val('1');
                    elem.attr('value', '1');
                    //console.log(['Updated checkbox',elem]); 
                }
                if (elem.attr('type') && elem.attr('type') == 'file') {

                    setTimeout(function() {
                        var cell_parent = elem.closest('.file-attachment-cell');
                        elem.appendTo(cell_parent);
                        elem.siblings().remove();
                        ReportForms.file_input(elem);
                    }, 100);
                }


            }); //for each field in detail
            //fix ckeditor, remove additional elements now

            //Get title
            var title = btn.parent().parent().find('div.complex-question-title > span').html();
            var details_container = $(
                '<div class="col-sm-12 no-padding no-margin"><div class="col-sm-12 space-102"></div><div class="widget-title"><span style="padding: 6px;" class="pull-left bigger-120 bolder  blue lighter ">' +
                title + ' ' + count + '</span>');
            details_container.append(details);
            //Add details section
            $('#' + btn.data('question-details') + ':last').parent().append($(
                details_container));


            //re-create advanced fields
            createAdvancedFields();

            //post answers with answerNumber to add new answers to report
            parts = details.attr('id').split('_');

            //notify user that we have added
            jQuery.gritter.add({
                title: 'A new section for ' + title + ' is added!',
                //text: 'A new section for '+title+' is added!',
                //image: 'path/to/image',
                sticky: false,
                time: 3000,
                class_name: 'gritter-success gritter-light '
            });

            return false;
        })
    }); //add-more-btn handler


    //fix input style on window resize 
    resizeInputs();
    $(window).resize(function() {
        resizeInputs();
    });


    //TODO FIXME WE May Need this
    //$('.submit-btn').on('click',preSaveAction);    

}); //questions setup script

function resizeInputs() {
    var contentSize = $(".page-content").width();
    var xlargeInputField = 100 + $('.input-xlarge').width();
    if ($('.input-xlarge').length > 0 && contentSize < xlargeInputField) {
        $('.input-xlarge').addClass('input-large').removeClass('input-xlarge');
    }
}

function showErrorAlert(reason, detail) {
    var msg = '';
    if (reason === 'unsupported-file-type') {
        msg = "Unsupported format " + detail;
    } else {
        //console.log("error uploading file", reason, detail);
    }
    $('<div class="alert"> <button type="button" class="close" data-dismiss="alert">&times;</button>' +
        '<strong>File upload error</strong> ' + msg + ' </div>').prependTo('#alerts');
}

$(function() {
    CustomSelect2.createSimple({
        placeholder: "Select Department",
        url: '<?=$this->url("config/user-departments")?>',
        id: 'id',
        label: 'department_name',
        element: $('#department'),
        data_target: 'data',
    });

});
$(function() {
    CustomSelect2.createSimple({
        placeholder: "Select Branch",
        url: '<?=$this->url("config/user-branches")?>',
        id: 'id',
        label: 'branch_name',
        element: $('#branch'),
        data_target: 'data',
    });

});
$(function() {
    CustomSelect2.createSimple({
        placeholder: "Select Month",
        url: '<?=$this->url("config/periods")?>?filter=last',
        id: 'period_code',
        label: 'period_code',
        element: $('#period_from'),
        data_target: 'data',
    });

});
$(function() {
    CustomSelect2.createSimple({
        placeholder: "Select Status",
        url: '<?=$this->url("config/config-value")?>?config_item=report_status&format=key-value',
        id: 'key',
        label: 'value',
        element: $('#report_status'),
        data_target: 'report_status',
    });

    $('#period_from').val('Jul-2020');
    $('#period_from').trigger('change');

    $('#report_status').val('draft');
    $('#report_status').trigger('change');
});
</script>