<table width="95%" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr> 
<hr color=#CEE3F6></td>

  </tr>
</table>
<table width="95%" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr> 
    <td bgcolor="#666666"><img src="/images/spacer.gif" width="1" height="1"></td>
    <td bgcolor="#666666"><img src="/images/spacer.gif" width="1" height="1"></td>
    <td bgcolor="#666666"><img src="/images/spacer.gif" width="1" height="1"></td>
  </tr>
  <tr> 
    <td width="1" bgcolor="#666666"><img src="/images/spacer.gif" width="1" height="35"></td>
    <td align="left" class="copyright"><table width="600" border="0" cellpadding="4" cellspacing="0">
        <tr>
          <td align="left" class="copyright">The official website of the Worldwide Ahmadiyya Muslim Community 
            is <a href="http://www.alislam.org" target="_blank">www.alislam.org</a><br>
            &copy; Copyright 2012 Ahmadiyya.ca - <a href="terms.php">Terms of 
            Use</a> </td>
        </tr>
      </table></td>
    <td width="1" bgcolor="#666666"><img src="/images/spacer.gif" width="1" height="1"></td>
  </tr>
  <tr> 
    <td width="1" bgcolor="#666666"><img src="/images/spacer.gif" width="1" height="1"></td>
    <td bgcolor="#666666"><img src="/images/spacer.gif" width="731" height="1"></td>
    <td width="1" bgcolor="#666666"><img src="/images/spacer.gif" width="1" height="1"></td>
  </tr>
</table>
