<table bgcolor="#e8e8e8"border="0" cellpadding="2" cellspacing="2" width="148">
	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="/index.php" CLASS="pageAltBlue"><SPAN CLASS="pageAltBlue">Home</SPAN></A></SPAN></TD></TR>
 
	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="http://www.alislam.org/" target="_blank" CLASS="pageAltBlue">Learn about Islam</A></SPAN></TD></TR>

	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="http://www.islam-ahmadiyya.org" target="_blank" CLASS="pageAltBlue">Islam - Francais</A></SPAN></TD></TR>

	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="http://www.islamevents.ca/" target="_blank" CLASS="pageAltBlue">Interfaith events & Symposiums</A></SPAN></TD></TR>

	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="http://www.booksonislam.org/" target="_blank" CLASS="pageAltBlue">Books on Islam</A></SPAN></TD></TR>

	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="http://www.mta.tv/" target="_blank" CLASS="pageAltBlue">Muslim Television Ahmadiyya</A></SPAN></TD></TR>

	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="/events.php" CLASS="pageAltBlue">Upcoming Events</A></SPAN></TD></TR>

	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="/prayers.php" CLASS="pageAltBlue">Prayer Timings</A></SPAN></TD></TR>
 
	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="/contact.php" CLASS="pageAltBlue">Contact Us</A></SPAN></TD></TR>

	<TR><TD>&nbsp;</TD></TR>

	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="/jalsa/" target=_blank CLASS="pageAltBlue">Jalsa Salana Canada</A></SPAN></TD></TR>

	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="/services/services.php" CLASS="pageAltBlue"><SPAN CLASS="pageAltBlue">Member Services</SPAN></A></SPAN></TD></TR>

	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="/daily.php" CLASS="pageAltBlue">Daily Knowledge</A></SPAN></TD></TR><tr>
 
	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="/list.php" CLASS="pageAltBlue">Join Mailing List</A></SPAN></TD></TR>

	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="/fridaysermons/" CLASS="pageAltBlue">Friday Sermons</A></SPAN></TD></TR>

	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="http://www.ahmadiyyagazette.ca/" target="_blank" CLASS="pageAltBlue">Ahmadiyya Gazette</A></SPAN></TD></TR>

	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="/today.php" CLASS="pageAltBlue">Day in Hijri and Shamsi</A></SPAN></TD></TR><tr>

	<TR><TD>&nbsp;</TD></TR>

	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="/useful_links.php" CLASS="pageAltBlue">Useful Links</A></SPAN></TD></TR>

	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="http://www.jamiaahmadiyya.ca/" target="_blank" CLASS="pageAltBlue">Jamia Ahmadiyya Canada</A></SPAN></TD></TR>

	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="/sundayschool/" CLASS="pageAltBlue">Sunday School</A></SPAN></TD></TR>
 
	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="/organizations.php" CLASS="pageAltBlue">Auxiliary Organizations</A></SPAN></TD></TR>
  
	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="/prof/prof_assoc.php" CLASS="pageAltBlue">Professional Associations</A></SPAN></TD></TR>

	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="http://www.humanityfirst.ca/" target="_blank" CLASS="pageAltBlue">Humanity First</A></SPAN></TD></TR>

	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="/jobbank/" CLASS="pageAltBlue">Job Search</A></SPAN></TD></TR>

	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="/jalsa/album.php" CLASS="pageAltBlue">Photo Galleries</A></SPAN></TD></TR>
 
<!--  
	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="/weather.php" CLASS="pageAltBlue">Weather</A></SPAN></TD></TR>

	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="/jalsa/topstories.php" CLASS="pageAltBlue">Top Stories</A></SPAN></TD></TR>
 
	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="/directory.php" CLASS="pageAltBlue">Events Directory</A></SPAN></TD></TR><tr>

	<TR><TD class="leftmenuitem"><SPAN CLASS="pageAltBlue"><A HREF="/members.php" CLASS="pageAltBlue">My Ahmadiyya.ca</A></SPAN></TD></TR> 
--> 
	<TR><TD>&nbsp;</TD></TR>


<!--   This table was automatically created with Macromedia Fireworks   -->
<!--   http://www.macromedia.com   -->
</table>
<!--<table>
<tr><td colspan="2">&nbsp</td></tr>
<tr><td colspan="2"><span class="rightColHeader">Branches:</span></td></tr>
<tr><td><select name="Branches" onchange="javascript:window.location.href('../brantford/')" onclick="javascript:window.location.href('../brantford/')">
	<option value="Brantford" selected>Brantford</option>
	</select>
	</td>
	<td><img src="../images/miscbuttons/go.gif" width="21" height="17" border="0" onclick="javascript:window.location.href('../brantford/')"></td>
</tr>
<tr><td colspan="2">&nbsp</td></tr>
<tr><td colspan="2"><span class="rightColHeader">Departments:</span></td></tr>
<tr><td><select name="Departments"  onchange="javascript:window.location.href('../dawat/dawat.php')" onclick="javascript:window.location.href('../dawat/dawat.php')">
	<option value="Tabligh" selected>Tabligh</option>
	</select>
	</td>
	<td><img src="../images/miscbuttons/go.gif" width="21" height="17" border="0" onclick="javascript:window.location.href('../dawat/dawat.php')"></td>
</tr>
</table>-->
<table width="148" border="0" cellpadding="0" cellspacing="0">
    <tr>
      <td class="pageheader"><span class="rightColHeader">Departments: </span>
      <table width="100%" border="0" cellspacing="0" cellpadding="2">
          <tr>
          <td><select name="branches" onchange="BranchHomePage(this.value)" style="font:12px">
          <option value="">Select department</option>
          <option value="sanatotijarat">Sanat-o-tijarat</option>
          <option value="talim">Ta`lim</option>
          <option value="taqwa">Ta`limul Qur`an</option>
          <option value="tarbiyat">Tarbiyat</option>
          <option value="waqfnau">Waqf Nau</option>
		  <?/*
	  	  $query1 = "SELECT branch_name,lcase(replace(branch_name,' ','')) url FROM ami_branches WHERE status = '1' and branch_code != 'CA' order by branch_name";
		  $result1 = @mysql_db_query($dbname,$query1);
		  while ($row1 = mysql_fetch_array($result1))
		  {
		  	print "<option value=\"" . $row1['url'] . "\">" . $row1['branch_name'] . "</option>";
		  } */?>
		  </select>
		</td>
        </tr>
        </table>
     </td>
    </tr>
</table>
