<table border="0" cellpadding="0" cellspacing="0" width="148">
	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="/index.php" CLASS="topmenutext"><SPAN CLASS="pageAltBlue">Home</SPAN></A></SPAN></TD></TR>
 
	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="http://www.alislam.org/" target="_blank" CLASS="topmenutext">Learn about Islam</A></SPAN></TD></TR>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="http://www.islam-ahmadiyya.org" target="_blank" CLASS="topmenutext">Islam - Francais</A></SPAN></TD></TR>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="http://www.islamevents.ca/" target="_blank" CLASS="topmenutext">Interfaith events & Symposiums</A></SPAN></TD></TR>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="http://www.booksonislam.org/" target="_blank" CLASS="topmenutext">Books on Islam</A></SPAN></TD></TR>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="http://www.mta.tv/" target="_blank" CLASS="topmenutext">Muslim Television Ahmadiyya</A></SPAN></TD></TR>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="/events.php" CLASS="topmenutext">Upcoming Events</A></SPAN></TD></TR>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="/prayers.php" CLASS="topmenutext">Prayer Timings</A></SPAN></TD></TR>
 
	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="/contact.php" CLASS="topmenutext">Contact Us</A></SPAN></TD></TR>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD>&nbsp;</TD></TR>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="/jalsa/" target=_blank CLASS="topmenutext">Jalsa Salana Canada</A></SPAN></TD></TR>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="/services/services.php" CLASS="topmenutext"><SPAN CLASS="pageAltBlue">Member Services</SPAN></A></SPAN></TD></TR>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="/daily.php" CLASS="topmenutext">Daily Knowledge</A></SPAN></TD></TR><tr>
 
	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="/list.php" CLASS="topmenutext">Join Mailing List</A></SPAN></TD></TR>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="/fridaysermons/" CLASS="topmenutext">Friday Sermons</A></SPAN></TD></TR><tr>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="http://www.ahmadiyyagazette.ca/" target="_blank" CLASS="topmenutext">Ahmadiyya Gazette</A></SPAN></TD></TR>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="/today.php" CLASS="topmenutext">Day in Hijri and Shamsi</A></SPAN></TD></TR><tr>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD>&nbsp;</TD></TR>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="/useful_links.php" CLASS="topmenutext">Useful Links</A></SPAN></TD></TR>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="http://www.jamiaahmadiyya.ca/" target="_blank" CLASS="topmenutext">Jamia Ahmadiyya Canada</A></SPAN></TD></TR>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="/sundayschool/" CLASS="topmenutext">Sunday School</A></SPAN></TD></TR>
 
	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="/organizations.php" CLASS="topmenutext">Auxiliary Organizations</A></SPAN></TD></TR>
  
	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="/prof/prof_assoc.php" CLASS="topmenutext">Professional Associations</A></SPAN></TD></TR>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="http://www.humanityfirst.ca/" target="_blank" CLASS="topmenutext">Humanity First</A></SPAN></TD></TR>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="/jobbank/" CLASS="topmenutext">Job Search</A></SPAN></TD></TR>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="/jalsa/album.php" CLASS="topmenutext">Photo Galleries</A></SPAN></TD></TR>
 
<!--  
	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="/weather.php" CLASS="topmenutext">Weather</A></SPAN></TD></TR>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="/jalsa/topstories.php" CLASS="topmenutext">Top Stories</A></SPAN></TD></TR>
 
	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="/directory.php" CLASS="topmenutext">Events Directory</A></SPAN></TD></TR><tr>

	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD class="leftmenuitem"><SPAN CLASS="topmenutext"><A HREF="/members.php" CLASS="topmenutext">My Ahmadiyya.ca</A></SPAN></TD></TR> 
--> 
	<TR><TD class="leftsap"><IMG SRC="images/menugrey.gif" WIDTH=148 HEIGHT=1 BORDER=0></TD></TR>
	<TR><TD>&nbsp;</TD></TR>


<!--   This table was automatically created with Macromedia Fireworks   -->
<!--   http://www.macromedia.com   -->
</table>
<!--<table>
<tr><td colspan="2">&nbsp</td></tr>
<tr><td colspan="2"><span class="rightColHeader">Branches:</span></td></tr>
<tr><td><select name="Branches" onchange="javascript:window.location.href('../brantford/')" onclick="javascript:window.location.href('../brantford/')">
	<option value="Brantford" selected>Brantford</option>
	</select>
	</td>
	<td><img src="../images/miscbuttons/go.gif" width="21" height="17" border="0" onclick="javascript:window.location.href('../brantford/')"></td>
</tr>
<tr><td colspan="2">&nbsp</td></tr>
<tr><td colspan="2"><span class="rightColHeader">Departments:</span></td></tr>
<tr><td><select name="Departments"  onchange="javascript:window.location.href('../dawat/dawat.php')" onclick="javascript:window.location.href('../dawat/dawat.php')">
	<option value="Tabligh" selected>Tabligh</option>
	</select>
	</td>
	<td><img src="../images/miscbuttons/go.gif" width="21" height="17" border="0" onclick="javascript:window.location.href('../dawat/dawat.php')"></td>
</tr>
</table>-->
<table><tr><td><img src="../images/spacer.gif" width="146" height="1"></td></tr></table>
<table width="148" border="0" cellpadding="0" cellspacing="0">
    <tr>
      <td class="pageheader"><span class="rightColHeader">Departments: </span>
      <table width="100%" border="0" cellspacing="0" cellpadding="2">
          <tr>
          <td><select name="branches" onchange="BranchHomePage(this.value)" style="font:12px">
          <option value="">Select department</option>
          <option value="ishaat">Ishaa`t</option>
          <option value="sanatotijarat">Sanat-o-tijarat</option>
          <option value="talim">Ta`lim</option>
          <option value="taqwa">Ta`limul Qur`an</option>
          <option value="tarbiyat">Tarbiyat</option>
          <option value="waqfnau">Waqf Nau</option>
          <option value="zirat">Zira`at</option>
		  <?/*
	  	  $query1 = "SELECT branch_name,lcase(replace(branch_name,' ','')) url FROM ami_branches WHERE status = '1' and branch_code != 'CA' order by branch_name";
		  $result1 = @mysql_db_query($dbname,$query1);
		  while ($row1 = mysql_fetch_array($result1))
		  {
		  	print "<option value=\"" . $row1['url'] . "\">" . $row1['branch_name'] . "</option>";
		  } */?>
		  </select>
		</td>
        </tr>
        </table>
     </td>
    </tr>
</table>
<table><tr><td><img src="../images/spacer.gif" width="146" height="1"></td></tr>
<tr><td>
<!--<hr>
<a href="http://jalsa.ahmadiyya.ca">
<img src="/jalsa/images/jalsa_sm.jpg" width=145 border=0>
</a>
-->
<hr>
 <a href="http://www.ahmadiyya.ca/downloads/Peaceful_Message.pdf">
<img src="https://www.ahmadiyya.ca/images/home/peace_msg.png" width=145 border=0>
</a>
<hr>
 <a href="http://www.mta.tv">
<img src="https://www.ahmadiyya.ca/images/home/mtalogo.jpg" width=145 border=0>
</a>
</td></tr></table>
