<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />

        <?php echo $this->headTitle($this->translate('Login | AMJ Canada Reporting System'))->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0')
            ->appendName('description', $this->translate('User login page'))
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1')
        ?>

		<!-- bootstrap & fontawesome -->
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/ace-fonts.css')
						->prependStylesheet($this->basePath() . '/assets/css/ace.min.css')
						->prependStylesheet($this->basePath() . '/assets/css/ace-rtl.min.css')
						->prependStylesheet($this->basePath() . '/assets/css/ace.onpage-help.css')
						->prependStylesheet($this->basePath() . '/assets/css/ace-part2.min.css','text/css', array('conditional' => 'lt IE 9',))
						->prependStylesheet($this->basePath() . '/assets/css/ace-ie.min.css','text/css', array('conditional' => 'lt IE 9',))
			;				
		 ?>


		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/assets/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/assets/js/respond.min.js',   'text/javascript', array('conditional' => 'lt IE 9',))
			;
         ?>

        <!--[if !IE]> -->
            <script type="text/javascript">
                window.jQuery || document.write("<script src='<?php echo $this->basePath() . "/assets/js/jquery.min.js"?>'>"+"<"+"/script>");
            </script>
        <!-- <![endif]-->

        <!--[if IE]>
            <script type="text/javascript">
             window.jQuery || document.write("<script src='<?php echo $this->basePath() . "/assets/js/jquery1x.min.js"?>'>"+"<"+"/script>");
            </script>
        <![endif]-->

        <script type="text/javascript">
            if('ontouchstart' in document.documentElement) document.write("<script src='<?php echo $this->basePath() . "/assets/js/jquery.mobile.custom.min.js"?>'>"+"<"+"/script>");
        </script>
        <script src='<?php echo $this->basePath() . "/assets/js/bootstrap.min.js" ?>'></script>

        <!-- ace scripts -->
        <script src='<?php echo $this->basePath() . "/assets/js/ace-elements.min.js" ?>'></script>
        <script src='<?php echo $this->basePath() . "/assets/js/ace.min.js"?>'></script>


	</head>

	<body class="login-layout light-login">
		<div class="main-container">
			<div class="main-content">
				<div class="row">
					<div class="col-sm-10 col-sm-offset-1">
						<div class="login-container">
							<div class="space-24"></div>
							<div class="center">
								<img alt="AMJ Canada" title="AMJ Canada" src='<?php echo $this->basePath()."/img/topbar-left1.png" ?>'/>
								<h3>
									<i class="fa fa-lock green"></i>
									<span class="blue" id="id-text2">Reporting System</span>
								</h3>
							</div>

							<div class="space-6"></div>
                            
                            <!-- / FLASH Messages -->
                            
							<!-- PAGE CONTENTS -->
                            <!-- FLASH Messages -->
                                <div>
                                    <?php
                                    $flash = $this->flashMessenger();
                                     echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                                     echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                                     echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                                     echo $flash->render('info',  array('alert', 'alert-dismissable', 'alert-info'));
                                     ?>
                                </div>
								
								<?php echo $this->content ?>

							<!-- / PAGE CONTENTS -->
							<!--
							<div class="navbar-fixed-top align-right">
								<br />
								&nbsp;
								<a id="btn-login-dark" href="#">Dark</a>
								&nbsp;
								<span class="blue">/</span>
								&nbsp;
								<a id="btn-login-blur" href="#">Blur</a>
								&nbsp;
								<span class="blue">/</span>
								&nbsp;
								<a id="btn-login-light" href="#">Light</a>
								&nbsp; &nbsp; &nbsp;
							</div>
							-->
						</div>
					</div><!-- /.col -->
				</div><!-- /.row -->
			</div><!-- /.main-content -->
		</div><!-- /.main-container -->

		<!-- basic scripts -->

		<!--[if !IE]> -->
			<script type="text/javascript">
				window.jQuery || document.write("<script src='<?php echo $this->basePath()."/assets/js/jquery.min.js" ?>'>"+"<"+"/script>");
			</script>

		<!-- <![endif]-->

		<!--[if IE]> 
			<script type="text/javascript">
			 window.jQuery || document.write("<script src='<?php echo $this->basePath()."/assets/js/jquery1x.min.js" ?>'>"+"<"+"/script>");
			</script>
		<![endif]-->
		<script type="text/javascript">
			if('ontouchstart' in document.documentElement) document.write("<script src='<?php echo $this->basePath()."/assets/js/jquery.mobile.custom.min.js" ?>'>"+"<"+"/script>");
		</script>
		
		<!-- Start inline-->
		<?php echo $this->inlineScript() ?>
		<!-- Done inline-->
	</body>
</html>
