<?php
$encoding='ISO-8859-1';
$encoding='UTF-8';

// disabling client-side cache
$this->headMeta()->appendHttpEquiv('expires',
                                   'Wed, 26 Feb 1997 08:21:57 GMT')
                 ->appendHttpEquiv('pragma', 'no-cache')
                 ->appendHttpEquiv('Cache-Control', 'no-cache');

// setting content type and character set
$this->headMeta()->appendHttpEquiv('Content-Type',
                                   'text/html; charset='.$encoding)
                 ->appendHttpEquiv('Content-Language', 'en-US');

// setting character set in HTML5
$this->headMeta()->setCharset($encoding); // Will look like <meta charset="UTF-8">


$children = $this->viewModel()->getCurrent()->getChildren();
$currPage = $children[0];
 
/*Change text size to saved settings*/
$user = $this->zfcUserIdentity();
$zoom='';
$zoom_class=''; 
if(!empty($user) && is_object($user)){
    $zoom = $this->zfcUserIdentity()->getSettingValue('zoom');
}
?>

<?php if(!empty($zoom)):?>    
    <?php $zoom_class=$zoom;?>
    <?php $this->inlineScript()->captureStart();?>
    //highlight appropriate zoom button
    $(function(){
        $(".btn-text-size").removeClass("btn-white");
        $(".btn-text-size[data-zoom='<?=$zoom?>']").addClass("btn-white");
    });
    <?php $this->inlineScript()->captureEnd(); ?>
    
<?php endif?>


<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta charset="<?=$encoding?>" />

        <?php echo $this->headTitle($this->translate('AMJ Canada Reporting System'))->setAutoEscape(false) ?>

		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 
                                         'type' => 'image/vnd.microsoft.icon', 
                                         'href' => $this->basePath() . '/img/favicon.ico'))
        ?>


		<!-- bootstrap & fontawesome -->		
		<link rel="stylesheet" href='<?php echo $this->basePath() . "/assets/css/bootstrap.min.css" ?>' />
		<link rel="stylesheet" href='<?php echo $this->basePath() . "/assets/css/font-awesome.min.css" ?>' />
		
		<!-- text fonts -->
		<link rel="stylesheet" href='<?php echo $this->basePath() . "/assets/css/ace-fonts.css"  ?>'/>

        <!-- JQuery UI must be before Bootstrap -->
        <link type="text/css" rel="stylesheet" class="ajax-stylesheet" href='<?php echo $this->basePath() . "/assets//css/jquery-ui.custom.min.css" ?>'>     

		<!-- ace styles -->

        <link type="text/css" rel="stylesheet" class="ajax-stylesheet" href='<?php echo $this->basePath() . "/assets/css/jquery.gritter.css" ?>'>     

        <link type="text/css" rel="stylesheet" class="ajax-stylesheet" href='<?php echo $this->basePath() . "/css/daterangepicker-bs3.css" ?>'>     

        <link rel="stylesheet" href='<?php echo $this->basePath() . "/assets/css/select2.css" ?>' />

		<link rel="stylesheet" href='<?php echo $this->basePath() . "/assets/css/ace.min.css" ?>' id="main-ace-style" />

		<!--[if lte IE 9]>
			<link rel="stylesheet" href='<?php echo $this->basePath() . "/assets/css/ace-part2.min.css"  ?>'/>
		<![endif]-->
		
        <link rel="stylesheet" href='<?php echo $this->basePath() . "/assets/css/ace-skins.min.css"?>' />

        <link rel="stylesheet" href='<?php echo $this->basePath() . "/assets/css/datepicker.css" ?>' />

    
        <link rel="stylesheet" href='<?php echo $this->basePath() . "/assets/css/ace-skins.min.css" ?>' />

        <link rel="stylesheet" href='<?php echo $this->basePath() . "/css/style.css" ?>' />



		<!--[if lte IE 9]>
		  <link rel="stylesheet" href='<?php echo $this->basePath() . "/assets/css/ace-ie.min.css" ?>' />
		<![endif]-->
 


		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

		<!--[if lte IE 8]>
		<script src='<?php echo $this->basePath() . "/assets/js/html5shiv.js" ?>'></script>
		<script src='<?php echo $this->basePath() . "/assets/js/respond.min.js" ?>'></script>
		<![endif]-->
		


        <!-- basic scripts -->
        <!--[if !IE]> -->
            <script type="text/javascript">
                window.jQuery || document.write("<script src='<?php echo $this->basePath() . "/assets/js/jquery.min.js"?>'>"+"<"+"/script>");
            </script>
        <!-- <![endif]-->

        <!--[if IE]>
            <script type="text/javascript">
             window.jQuery || document.write("<script src='<?php echo $this->basePath() . "/assets/js/jquery1x.min.js"?>'>"+"<"+"/script>");
            </script>
        <![endif]-->

        <script type="text/javascript">
            if('ontouchstart' in document.documentElement) document.write("<script src='<?php echo $this->basePath() . "/assets/js/jquery.mobile.custom.min.js"?>'>"+"<"+"/script>");
        </script>


        <!-- JQuery UI must be before Bootstrap -->
        <script src='<?php echo $this->basePath() . "/assets/js/jquery-ui.min.js" ?>'></script>

        <script src='<?php echo $this->basePath() . "/assets/js/bootstrap.min.js" ?>'></script>

        <script src="<?=$this->basePath()?>/assets/js/bootbox.min.js"></script>

        <!-- ace settings handler -->
        <script src='<?php echo $this->basePath() . "/assets/js/ace-extra.min.js" ?>'></script>
        <script src='<?php echo $this->basePath() . "/assets/js/ace/ace.settings.js" ?>'></script>



        <script src='<?php echo $this->basePath() . "/assets/js/jquery.ui.touch-punch.min.js" ?>'></script>

        <script src='<?php echo $this->basePath() . "/assets/js/bootstrap-wysiwyg.min.js" ?>'></script>

        <script src='<?php echo $this->basePath() . "/assets/js/jquery.validate.min.js"?>'></script>
        
        <script src='<?php echo $this->basePath() . "/assets/js/jquery.form.min.js"?>'></script>

        <script type="text/javascript" src='<?php echo $this->basePath() . "/js/moment.min.js" ?>'></script>

        <!-- ace scripts -->
        <script src='<?php echo $this->basePath() . "/assets/js/ace.min.js"?>'></script>
        <script src='<?php echo $this->basePath() . "/assets/js/ace-elements.min.js" ?>'></script>

        <script src='<?php echo $this->basePath() . "/assets/js/additional-methods.min.js"?>'></script>


        <script src='<?php echo $this->basePath() . "/assets/js/select2.min.js"?>'></script>
        <script src='<?php echo $this->basePath() . "/js/custom.select2.js"?>'></script>
  
 
        <script src='<?php echo $this->basePath() . "/assets/js/jquery.gritter.min.js" ?>'></script>

       <script src='<?php echo $this->basePath() . "/assets/js/date-time/bootstrap-datepicker.min.js" ?>'></script>

        <!-- default creation scafolding for various plugins -->
        <script src='<?php echo $this->basePath() . "/js/reporting.additions.js" ?>'></script>



        <?php echo $this->headScript(); ?>

		<style>
		.navbar-brand-amj{
		    background-image: url('<?php echo $this->basePath()."/img/logo.png" ?>');
		    background-size: 40px 40px;
		    background-repeat:no-repeat;
		    background-position: 0px 2px; 
		    padding-left:50px;
		}

        .navbar>.container .navbar-brand, .navbar>.container-fluid .navbar-brand{
            margin-left:8px!important;
        }

		</style>

	</head>

	<body class="no-padding no-skin <?=$zoom_class?>">

		<!-- #section:basics/navbar.layout -->
		<div id="navbar" class="navbar navbar-default navbar-fixed-top container" style="margin: auto;">

			<script type="text/javascript">
				
				try{
                     // ace.settings.set('navbar_fixed', 'fixed',true);//@ ace-extra.js
                     // ace.settings.navbar_fixed(true, true,true);//@ ace-extra.js
                     // ace.settings.sidebar_fixed(true, true,true);//@ ace-extra.js
                     // ace.settings.set('main_container','fixed',true);//@ ace-extra.js
                     
				}catch(e){console.log(e);}
				
			</script>

			<div class="navbar-container no-padding top-nav-bar-container" id="navbar-container">
				<!-- #section:basics/sidebar.mobile.toggle -->

				<button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler">
					<span class="sr-only">Toggle sidebar</span>

					<span class="icon-bar"></span>

					<span class="icon-bar"></span>

					<span class="icon-bar"></span>
				</button>

				<!-- /section:basics/sidebar.mobile.toggle -->
				<div class="navbar-header pull-left no-margin" style="margin-left: 8px!important;">
					<!-- #section:basics/navbar.layout.brand -->
					&nbsp;
					<a href="http://www.ahmadiyya.ca" class="navbar-brand navbar-brand-amj smaller">
                        <!-- 
                            <img alt="AMJ Canada" title="AMJ Canada" src='<?php echo $this->basePath()."/img/logo.png" ?>'/>
                         -->
							AMJ Reporting System
					</a>
					<!-- /section:basics/navbar.layout.brand -->

					<!-- #section:basics/navbar.toggle -->

					<!-- /section:basics/navbar.toggle -->
				</div>
                  <button type="button" class="navbar-toggle collapsed  smaller-90 hide" data-toggle="collapse" data-target="#navbar-buttons-menu-id">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                  </button>

               <div class="bismillah">
                        <img src="/img/bismillah.png" height="30">
                </div>

				<!-- #section:basics/navbar.dropdown -->

				<div class="navbar-buttons pull-right collapse navbar-collapse no-padding no-margin" role="navigation" id="navbar-buttons-menu-id">

					<ul class=" nav ace-nav ">

                        <?php                
                         echo $this->
                            navigation('navigation')
                            ->menu()
                            ->setPartial('partial/top_menu.phtml')
                            ;                                  
                        ?>
                        <!-- #section:basics/navbar.user_menu -->
                        <!--
                        <li class="blue-light2">                      
                            < ? php include __DIR__.'/../partial/userinfo.phtml'  ? >
                        </li>
                        < ? php if($this->zfcUserIdentity()): ? >
                        < ? php endif ? >
                        -->
					</ul>
				</div>

				<!-- /section:basics/navbar.dropdown -->
			</div><!-- /.navbar-container -->
		</div>

		<!-- /section:basics/navbar.layout -->
		<div class="main-container responsive row-fluid container" id="main-container">


			<!-- #section:basics/sidebar -->
            <div id="sidebar" class="sidebar responsive sidebar-fixed  compact  " data-sidebar="true" data-sidebar-scroll="true" role="navigation">
               <div class="nav-wrap-up pos-rel">
                   <div class="nav-wrap">
                       <div id="sidebar-container-id" style="position: relative; top: 0px; transition-property: top; -webkit-transition-property: top; transition-duration: 0.15s; -webkit-transition-duration: 0.15s;">
                           <ul class=" nav nav-list">
            
                            <?php                
                             echo $this->
                                navigation('navigation')
                                ->menu()
                                ->setUlClass('nav navbar-nav')
                                ->setPartial('partial/navigation.phtml')
                                ;                                  
                            ?>                            
                            </ul>
                            
                            
                            <!-- ?php include __DIR__.'/../partial/settings_nav2.phtml'  ? -->
                            
                            
                       </div>
                   </div>                   
               </div>

                <!-- #section:basics/sidebar.layout.minimize -->
                <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse" style="z-index: 1;">
                    <i class="ace-icon fa fa-angle-double-left" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
                </div>
            
                <div class="nav-wrap-up pos-rel">
                        <!-- ? php include __DIR__.'/../partial/settings_nav.phtml'  ? -->
                </div>

                <!-- /section:basics/sidebar.layout.minimize -->
                <script type="text/javascript">
                    
                    $(document).ready(function(){
                    	if($('#sidebar > .nav-wrap-up > .nav-wrap > #sidebar-container-id .nav-list > li').size()<2){
                    		//hide side bar nothing to display
                    		$('#sidebar').hide();
                    		$('.main-content').css('margin-left','0px');
                    	}
                    });
                </script>
            </div>

			<!-- /section:basics/sidebar -->
			
			
			<div class="main-content">
                <div class="main-content-inner">
				<!-- /section:basics/content.breadcrumbs -->
				<div class="page-content" style="padding: 5px;">

					<div class="page-content-area no-padding-left">

                            <!-- FLASH Messages -->
                            	
                                <div class="col-xs-12 col-md-12 col-lg-12" style="z-index: 1000">
                                    <?php
                                    
                                    $flash = $this->flashMessenger();
                                    
                                    echo $flash->renderCurrent('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                                    echo $flash->renderCurrent('default', array('alert', 'alert-dismissable', 'alert-warning'));
                                    echo $flash->renderCurrent('success', array('alert', 'alert-dismissable', 'alert-success'));
                                    echo $flash->renderCurrent('info',  array('alert', 'alert-dismissable', 'alert-info'));
                                    echo $flash->renderCurrent('warning', array('alert', 'alert-dismissable', 'alert-warning'));
                                    
                                    $flash->getPluginFlashMessenger()->clearCurrentMessagesFromContainer();
                                    
                                     ?>
                                </div>


						<!-- page content goes here -->
	
	                       <?php echo $this->content; ?>

	
						
					</div><!-- /.page-content-area -->
					
				</div><!-- /.page-content -->
                </div>
			</div><!-- /.main-content -->


            <!-- #section:basics/footer -->
            <!--
			<div class="footer">
				<div class="footer-inner">
					<div class="footer-content">
						<span class="bigger-120">
							<span class="blue bolder">Ace</span>
							Application &copy; 2013-2014
						</span>

						&nbsp; &nbsp;
						<span class="action-buttons">
							<a href="#">
								<i class="ace-icon fa fa-twitter-square light-blue bigger-150"></i>
							</a>

							<a href="#">
								<i class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
							</a>

							<a href="#">
								<i class="ace-icon fa fa-rss-square orange bigger-150"></i>
							</a>
						</span>
					</div>

				</div>
			</div>
			-->
			<!-- /section:basics/footer -->

			<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
				<i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
			</a>
		</div><!-- /.main-container -->
            		
		
		
        
        <script>
            
            $(function(){

                if($('div.alert-danger>ul>li') && $('div.alert-danger>ul>li')[0] && $('div.alert-danger>ul>li')[0].innerHTML.includes("This username will not work as of May 20th, 2023.")){
                    $('div.alert-danger>ul>li').css("font-size","32pt")
                    $('div.alert-danger>ul>li').css("list-style-type","none")
                }


                if($.select2){
                    $('.select2').select2( {
                        minimumResultsForSearch: -1,
                        dropdownCssClass : 'no-search'                    
                    } );
                }
                
                $('#ace-settings-add-container').on('change',function(e){
                    
                    if( $('#ace-settings-add-container').length > 1 ){
                        console.log($('#ace-settings-add-container').prop('checked'));
                        if($('#ace-settings-add-container').prop('checked')){
                            $('#navbar').addClass('container');
                            $('#navbar-container').css('padding-left','8px;');
                        }else{
                            $('#navbar').removeClass('container');
                        }
                        
                    }
                    
                });                
            } );
            
        </script>

        <!-- Inline Scripts -->
        <?=$this->inlineScript();?>
        <!-- / Inline Scripts -->
        <script>
            
        </script>

<?php
    if(getenv('APPLICATION_ENV') != 'production'  ){
        echo '<footer><div style="height:inherit;min-height:inherit;text-align:center;color:white;z-index:99999" class="navbar navbar-inverse navbar-fixed-top label-warning">';
        echo 'ENV '.getenv('APPLICATION_ENV') . '&nbsp; from &nbsp;' . (ROOT_PATH);
        echo '</div></footer>';
    }

    if (getenv('APPLICATION_ENV') != 'production' //let's us test dev env in firefox without warning
        &&  strpos(strtolower($_SERVER['HTTP_USER_AGENT']), 'chrome') === false &&  strpos(strtolower($_SERVER['HTTP_USER_AGENT']), 'crios') === false ){
        $this->flashMessenger()->setNamespace('error')->addMessage('WARNING: This application works best on Google Chrome browser. Your current browser is not supported for the Reporting application. Please use the supported browser only to ensure no errors are encountered.');
    }
?>

<script type="text/javascript" src="https://aimscan.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-T/l24at6/b/0/a44af77267a987a660377e5c46e0fb64/_/download/batch/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector.js?locale=en-US&collectorId=0f0a16b2"></script>
</body>
</html>
