<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 
                                         'type' => 'image/vnd.microsoft.icon', 
                                         'href' => $this->basePath() . '/img/favicon.ico'))
        ?>


        <!-- bootstrap & fontawesome -->        
        <link rel="stylesheet" href='<?php echo $this->basePath() . "/assets/css/bootstrap.min.css" ?>' />
        <link rel="stylesheet" href='<?php echo $this->basePath() . "/assets/css/font-awesome.min.css" ?>' />
        
        <!-- ace css -->
        <link rel="stylesheet" href='<?php echo $this->basePath() . "/assets/css/ace.min.css"  ?>'/>

        <!-- text fonts -->
        <link rel="stylesheet" href='<?php echo $this->basePath() . "/assets/css/ace-fonts.css"  ?>'/>
	
        <!-- JQuery UI must be before Bootstrap -->
        <link type="text/css" rel="stylesheet" class="ajax-stylesheet" href='<?php echo $this->basePath() . "/assets//css/jquery-ui.custom.min.css" ?>'>     

        <!-- ace styles -->
        <link rel="stylesheet" href='<?php echo $this->basePath() . "/css/style.css" ?>' />
        <!-- basic scripts -->
        <!--[if !IE]> -->
            <script type="text/javascript">
                window.jQuery || document.write("<script src='<?php echo $this->basePath() . "/assets/js/jquery.min.js"?>'>"+"<"+"/script>");
            </script>
        <!-- <![endif]-->

        <!--[if IE]>
            <script type="text/javascript">
             window.jQuery || document.write("<script src='<?php echo $this->basePath() . "/assets/js/jquery1x.min.js"?>'>"+"<"+"/script>");
            </script>
        <![endif]-->

        <script type="text/javascript">
            if('ontouchstart' in document.documentElement) document.write("<script src='<?php echo $this->basePath() . "/assets/js/jquery.mobile.custom.min.js"?>'>"+"<"+"/script>");
        </script>


        <!-- JQuery UI must be before Bootstrap -->
        <script src='<?php echo $this->basePath() . "/assets/js/jquery-ui.min.js" ?>'></script>

        <script src='<?php echo $this->basePath() . "/assets/js/bootstrap.min.js" ?>'></script>

    </head>
<body>

<div class="col-xs-12 col-md-12 col-lg-12 no-padding no-margin ajax-contents">
    <!-- FLASH Messages -->                               
    <div class="col-xs-12 col-md-12 col-lg-12">
        <?php
        
        $flash = $this->flashMessenger();
        
        echo $flash->renderCurrent('error',   array('alert', 'alert-dismissable', 'alert-danger'));
        echo $flash->renderCurrent('default', array('alert', 'alert-dismissable', 'alert-warning'));
        echo $flash->renderCurrent('success', array('alert', 'alert-dismissable', 'alert-success'));
        echo $flash->renderCurrent('info',  array('alert', 'alert-dismissable', 'alert-info'));
        
        $flash->getPluginFlashMessenger()->clearCurrentMessagesFromContainer();
        
         ?>
    </div>    
    <div class="col-xs-12 col-md-12 col-lg-12 no-padding no-margin">
    <?php echo $this->content; ?>    
    </div>
</div>

<!-- Inline Scripts -->
<?=$this->inlineScript();?>
<!-- / Inline Scripts -->
</body>
</html>