<?php 
/* @var $paginator \Zend\Paginator\Paginator */
$paginator = $this->paginator;
?>
<!-- Start footer -->
<div class="row-fluid row" id="<?php echo $this->gridId; ?>_footer">

    <!-- mass actions -->
    <div class="span3 col-md-3">
        <?php 
        foreach($this->massActions as $action){
            /* @var $action \ZfcDatagrid\Action\Mass */
            ?>
            <a href="#" class="btn btn-default massAction" data-url="<?php echo $action->getLink(); ?>">
                <?php echo $this->translate($action->getTitle()); ?>
            </a>
            <?php
        }
        ?>
    </div>
    
    <!-- Pagination -->
    <div class="span6 col-md-6 text-center no-padding">
        <input type="hidden" name="<?php echo $this->parameterNames['currentPage']; ?>" value="<?php echo $this->paginator->getPages()->current; ?>" />
        <?php 
        echo $this->paginationcontrol($this->paginator, 'Elastic', 'partial/bootstrap_datagrid/paginator', array(
            'activeParameters' => $this->activeParameters, 
            'parameterNames' => $this->parameterNames,
            'gridId' => $this->gridId
        ));
        ?>
    </div>
    <!-- Info -->
    <div class="span3 col-md-3 text-right" style="padding-right: 15px;">
        <?php echo $this->translate('Showing').' '.$paginator->getCurrentItemCount().' '.$this->translate('of').' '.$paginator->getTotalItemCount().' '.$this->translate('item(s)'); ?><br />
        <?php echo $this->translate('Page') . ' ' . $paginator->getCurrentPageNumber() . ' ' . $this->translate('of') . ' ' .$paginator->count();?>
    </div>
</div><!-- End footer -->

<?php $this->inlineScript()->captureStart();?>
function <?php echo $this->gridId; ?>_toggleCheckboxes(element){
    var elements = document.getElementsByName('massActionSelected[]');
    
    var useThis = element.checked;
    for(i = 0; i < elements.length; i++){
        elements[i].checked = useThis;
    }
}

$( document ).ready(function() {
    $('#<?php echo $this->gridId; ?>_footer a.massAction').click( function() {
        var form = document.createElement('form');
        form.setAttribute('name', 'massAction');
        form.setAttribute('method', 'post');
        form.setAttribute('action', $(this).attr('data-url'));
        
        var checkboxes = document.getElementsByName('massActionSelected[]');
        for(i = 0; i < checkboxes.length; i++){
            var node = checkboxes[i].cloneNode();
            node.name = '<?php echo $this->parameterNames['massIds']; ?>[]';
            form.appendChild(node);
        }
        
        document.body.appendChild(form);
        form.submit();
        document.body.removeChild(form);
    });
});

<?php $this->inlineScript()->captureEnd(); ?>