<?php

    $this->headLink()
        ->appendStylesheet($this->basePath() . '/assets/css/select2.css')
        ->appendStylesheet($this->basePath().'/assets/css/datepicker.css');
  
  
    $this->headScript()->appendFile( $this->basePath() . '/assets/js/select2.min.js','text/javascript',array());
    $this->headScript()->appendFile( $this->basePath() . '/js/custom.select2.js','text/javascript',array());
    
    $this->headScript()->appendFile( $this->basePath() . '/assets/js/uncompressed/date-time/bootstrap-datepicker.js','text/javascript',array());
        

?>

<?php if ($this->header_part):?>        
    <?php echo $this->partial($this->header_part);?>
<?php endif?>

<form name="form_<?php echo $this->gridId; ?>" method="post" action="<?php echo $this->url(null, array(), array(), true); ?>" >

<input type="hidden" name="grid_name" value="<?php echo $this->gridId; ?>" />
<?php 
use ZfcDatagrid\Column\Type;

$hasMassActions = false;
if(count($this->massActions) > 0){
    $hasMassActions = true;
}
?>

<?php if ($this->daterangeEnabled): ?>
    <?php $this->inlineScript()->captureStart();?>
    $(function(){
        <?php //If daterange bootstrapTable filter is enable show it ?>
            $('input.daterange').daterangepicker(
            <?= Zend\Json\Json::encode($this->daterangeParameters, false, array('enableJsonExprFinder' => true)); ?>
            ).on('apply.daterangepicker', function(ev,picker){
                this.form.submit();
            });
            
    });
    <?php $this->inlineScript()->captureEnd(); ?>
<?php endif; ?>

<?php $this->inlineScript()->captureStart();?>
$(function(){

        $('#simple-colorpicker-1').ace_colorpicker({pull_right:true}).on('change', function(){
            var color_class = $(this).find('option:selected').data('class');
            var new_class = 'widget-box';
            if(color_class != 'default')  new_class += ' widget-color-'+color_class;
            
            $(this).closest('.widget-box').attr('class', new_class);
        });

});
<?php $this->inlineScript()->captureEnd(); ?>

<div class="widget-box widget-color-blue2">
<div class="widget-header">
    <h4 class="widget-title "><i class="ace-icon fa fa-table"></i></class="ace-icon"><?=$this->title?></h4>

    <div class="widget-toolbar widget-toolbar-blue no-border">
        <a href="#" data-action="collapse" >
            <i class="ace-icon fa fa-chevron-up"></i>
        </a>
    </div>

    <div class="widget-toolbar widget-toolbar-blue no-border ">
        <?php 
        if(is_array($this->title_filters)){
            foreach ($this->title_filters as $filter) {
                echo $this->partial('partial/bootstrap_datagrid/custom_filters/'.$filter);
            }    
        }
        ?>
    </div>

    <?php if ($this->templateToolbar):?>        
        <?php echo $this->partial($this->templateToolbar,array('columns'=>$this->columns));?>
    <?php endif?>
    
</div> <!-- //widget-header -->

  <div class="widget-body no-padding no-margin">
    
    <div class="widget-main  no-padding no-margin">                
    <?php 
    $orderOnclick = 'document.forms[\'form_'.$this->gridId.'\'].elements[\'' . $this->parameterNames['sortColumns'] . '\'].value = \'%s\';';
    $orderOnclick .= 'document.forms[\'form_'.$this->gridId.'\'].elements[\'' . $this->parameterNames['sortDirections'] . '\'].value = \'%s\';';
    $orderOnclick.= 'document.forms[\'form_'.$this->gridId.'\'].submit(); return false;';
    
    $classes = array('table', 'table-striped', 'table-bordered2','table-hover','table-condensed','table-normal','table-datagrid');
    if($this->rowClickAction !== null){
        $classes[] = 'table-hover';
    }
    ?>

    <table class="<?php echo implode(' ', $classes); ?>">
        <thead>
        <tr style="background-color: #EEE">
            <?php 
            if($hasMassActions === true){
                echo '<th><input type="checkbox" onclick="' . $this->gridId . '_toggleCheckboxes(this);" /></th>';
            }
            
            foreach($this->columns as $col){
                /* @var $col \ZfcDatagrid\Column\AbstractColumn */
                $classes = array();
                $styles = array();
                
                $id = $col->getUniqueId();
                
                $label = '';
                if($col->getLabel() != ''){
                    $label = $this->translate($col->getLabel());
                }
                
                $width = $col->getWidth();
                if($width != ''){
                    $styles[] = 'width: '.$this->escapehtmlattr($width).'%';
                }
                
                
                if($col->isHidden() === true){
                    $classes[] = 'hidden';
                }
                if($this->custom_classes && isset($this->custom_classes[$col->getUniqueId()])){
                    $classes[]=$this->custom_classes[$col->getUniqueId()];
                }
                if($col->getType() instanceof Type\Number){
                    $styles[] = 'text-align: right';
                }
                ?>
                <th id="<?php echo $this->escapehtmlattr($id); ?>" class="<?php echo implode(',', $classes); ?>" style="<?php echo implode(';', $styles); ?>">
                    
                    <?php if($col->isUserSortEnabled() === true): 
                        if($col->isSortActive() === true && $col->getSortActiveDirection() === 'ASC'){
                            $direction = 'DESC';
                        } else{
                            $direction = 'ASC';
                        }
                        ?>
                        <a href="<?php echo 
                            $this->url(null, 
                                array(),
                                array(
                                    'query' => array_merge($this->activeParameters, array(
                                            $this->parameterNames['sortColumns'] => $col->getUniqueId(),
                                            $this->parameterNames['sortDirections'] => $direction,
                                        )
                                    )
                                ),
                                true
                            );?>
                        " onclick="<?php echo sprintf($orderOnclick, $col->getUniqueId(), $direction); ?>">
                            <?php echo $this->escapeHtml($label); ?>
                        </a>
                    <?php else: ?>
                        <?php echo $this->escapeHtml($label); ?>
                    <?php endif; ?>
                    
                    <?php 
                    if($col->isSortActive() === true){
                        if($col->getSortActiveDirection() === 'ASC'):?>
                            <i class="icon-chevron-down glyphicon glyphicon-chevron-down"></i>
                        <?php else: ?>
                            <i class="icon-chevron-up glyphicon glyphicon-chevron-up"></i>
                        <?php endif;
                    }
                    ?>
                </th>
                <?php
            }
            ?>
        </tr>
        
        <!-- User filters -->
        <?php if($this->isUserFilterEnabled === true):?>
            <tr style="background-color: #EEE">
                <?php
                if($hasMassActions === true){
                    echo '<td></td>';
                }
                foreach($this->columns as $col){
                    /* @var $col \ZfcDatagrid\Column\AbstractColumn */

                    $classes = array();
                    if($col->isHidden() === true){
                        $classes[] = 'hidden';
                    }
                    if($this->custom_classes && isset($this->custom_classes[$col->getUniqueId()])){
                        $classes[]=$this->custom_classes[$col->getUniqueId()];
                    }
                    
                    $htmlFilter = '';
                    if ($col->isUserFilterEnabled() === true) {

                        if($this->custom_filters && isset($this->custom_filters[$col->getUniqueId()])){
                            
                           $partial_name=$this->custom_filters[$col->getUniqueId()]; 
                            
                           $this->col=$col;                           
                                                     
                           $htmlFilter=$this->partial('partial/bootstrap_datagrid/custom_filters/'.$partial_name); 
                                                       
                        }else if ($col->hasFilterSelectOptions() === true) {
                            $htmlFilter = '<select name="toolbarFilters[' . $col->getUniqueId() . ']" style="width: 80%" onchange="this.form.submit()" class="form-control2 select2" >';
                            foreach ($col->getFilterSelectOptions() as $value => $option) {
                                if ($col->getFilterActiveValue() == sprintf($col->getFilterDefaultOperation(), $value)) {
                                    $htmlFilter .= '<option value="' . $value . '" selected="selected">' . $option . '</option>';
                                } else if (($col->getFilterActiveValue() === '') && ($value === '')){
                                    $htmlFilter .= '<option value="' . $value . '" selected="selected">' . $option . '</option>';
                                } else {
                                    $htmlFilter .= '<option value="' . $value . '">' . $option . '</option>';
                                }
                            }
                            $htmlFilter .= '</select>';

                        } else if ($col->getType() instanceof \ZfcDatagrid\Column\Type\DateTime){
                            $htmlFilter = '<input type="text" name="toolbarFilters[' . $col->getUniqueId() . ']" style="width: 80%" value="' . $col->getFilterActiveValue() . '" class="form-control daterange" />';
                        } else {
                            $htmlFilter = '<input type="text" name="toolbarFilters[' . $col->getUniqueId() . ']" style="width: 80%" value="' . $col->getFilterActiveValue() . '" class="form-control" />';
                        }
                    }
                    ?>
                    <td class="<?php echo implode(',', $classes); ?>">
                        <?php echo $htmlFilter; ?>
                    </td>
                    <?php
                }
                ?>
            </tr>
        <?php endif; ?>
    </thead><!-- END table header -->
     
    <!-- Start table BODY -->
    <tbody>
        <?php foreach($this->data as $row): ?>
            <?php echo $this->bootstrapTableRow($row, $this->columns, $this->rowClickAction, $this->rowStyles, $hasMassActions); ?>
        <?php endforeach; ?>
    </tbody>
    </table>
    
    </div> <!-- //widget-main -->  


    <?php if(! $this->data_only) :?>
    <div class="widget-toolbox padding-8 clearfix">
        <?php echo $this->partial('partial/bootstrap_datagrid/footer'); ?>
    </div><!--Toolbox as footer -->
    <?php endif?>
    
    <div class="hidden">
        <input type="submit" style="width: 0px; height:0px; margin: 0; padding: 0; border: 0;" name="hiddenSubmit" />
        <input type="hidden" name="<?php echo $this->parameterNames['sortColumns']; ?>" value="<?php echo $this->activeParameters[$this->parameterNames['sortColumns']]; ?>" />
        <input type="hidden" name="<?php echo $this->parameterNames['sortDirections']; ?>" value="<?php echo $this->activeParameters[$this->parameterNames['sortDirections']]; ?>" />
    </div>
</div> <!-- //widget-body -->

</div><!-- //widget-box -->
</form>
