<?php

?>

<form class="form-horizontal" role="form" id="update-enc-field" method="post" action="<?php echo $this->url("config/update-enc-field") ?>"  >

<div class="row">
    <div class="col-xs-12 col-lg-12 " >

       <div class="form-group">
          <label class="col-sm-4 control-label no-padding-right" for="full_name">Table Name:</label>
          <div class="col-sm-7">
            <input type="text" class="form-control input-xlarge" placeholder="" id="table" name="table"  required="true" value="<?=$data?$data['table']:''?>"></input>
          </div>
       </div>
       
       <div class="form-group">
          <label class="col-sm-4 control-label no-padding-right" for="full_name">Field Name:</label>
          <div class="col-sm-7">
            <input type="text" class="form-control input-xlarge" placeholder="" id="field" name="field"  required="true" value="<?=$data?$data['field']:''?>"></input>
          </div>
       </div>
       

       <div class="form-group">
          <label class="col-sm-4 control-label no-padding-right" for="full_name">Record Id:</label>
          <div class="col-sm-7">
            <input type="text" class="form-control input-xlarge" placeholder="" id="id" name="id"  required="true" value="<?=$data?$data['id']:''?>"></input>
          </div>
       </div>


       <div class="form-group">
          <label class="col-sm-4 control-label no-padding-right" for="value">Field Value<?=$data?" ($data[field])":''?>:</label>
          <div class="col-sm-7">
            <textarea  cols="50" rows="10" name="value"><?=$value?></textarea>
          </div>
       </div>
       <input type="hidden"  class="hidden" name="oper" value="load" id="oper" />
       <div class="form-group ">
          <div class="col-sm-4" >
          </div>
          <div class="col-sm-7">
                <button class="button btn btn-primary btn-round btn-white" type="submit">Load</button>
                <button class="button btn btn-success btn-round btn-white update" type="submit">Update</button>
          </div>
       </div>


    </div>
</div>

</form>

<script>
    $(
        function(){
            $('.update').on('click',function(){ $('#oper').val('update'); });
        }
    );
</script>