<?php
use Zend\Validator\EmailAddress;

return array(
        'hydrator'  => 'Zend\Stdlib\Hydrator\ArraySerializable',
        'fieldsets' => array(
             array(
               'spec'=>array(
                    'name' => 'reset_password',
                    'elements' => array(
                                    array(
                                      'spec'=>array(
                                        'name' => 'username',
                                        'type' => 'text',
                                        'options' => array(
                                            'label' => '',
                                            ),
                                        'attributes' => array(
                                            'placeholder'=>'Username / UserId',
                                            'type'  => 'text'
                                        ),
                                        )
                                    ),
                                    array(
                                    'spec'=>array(
                                        'type' => 'Zend\Form\Element\Email',
                                        'name' => 'email',
                                        'attributes' => array(
                                            'placeholder'=>'Email linked to account',
                                            ),
                                        'options' => array(
                                            'label' => '',
                                            ),
                                    ),
                                 ),
                                array(
                                    'spec'=>array(
                                        'type' => 'password',
                                        'name' => 'member_code',
                                        'attributes' => array(
                                            'placeholder'=>'Member Code',
                                            ),
                                        'options' => array(
                                            'label' => '',
                                            ),
                                    ),
                                 ),
                       ),
                ),
            
             ),
        /*
        array(
            'name' => 'details',
            'elements' => array(
                array(
                    'name' => 'subject',
                    'options' => array(
                        'label' => 'Subject',
                        ),
                    'attributes' => array(
                        'type'  => 'text',
                    ),
                ),
                array(
                    'type' => 'Zend\Form\Element\Textarea',
                    'options' => array(
                        'label' => 'Message',
                        ),
                ),
            ),
        ),
         */
    ),
    /*
    'elements' => array(
        array(
            'type' => 'Zend\Form\Element\Captcha',
            'name' => 'captcha',
            'options' => array(
                'label' => 'Please verify you are human. ',
                'captcha' => array(
                    'class' => 'Dumb',
                ),
            ),
        ),
        array(
            'type' => 'Zend\Form\Element\Csrf',
            'name' => 'security',
        ),
        array(
            'name' => 'send',
            'attributes' => array(
                'type'  => 'submit',
                'value' => 'Submit',
            ),
        ),
    ),
*/
    // Configuration to pass on to
    // Zend\InputFilter\Factory::createInputFilter()
    'input_filter' => array(
        //'type' => 'Zend\InputFilter\InputFilter',
        /* ... */
 
    )
);