<?php
    
    $redirect_parts=explode('?',urldecode($this->target));
    $base_part=$redirect_parts[0];
    $query_part='?'.(count($redirect_parts)>1?$redirect_parts[1]:'');

    if($base_part==''){
        $base_part='home/members';
    }
?>

                              <form action="<?=$this->url('auth/change-password')?>" method="post">

                            <h3 class="title blue">Change Password </h3>

                              <table width="275" border="0">
                                <tr>
                                  <!--  
                                  <td width="16%">
                                     <select name="use_email" class="newstyleselect">
                                        <option value="0" selected class="newstyletxt">User ID</option>
                                        <option value="1" >Email</option>
                                        </select>
                                    </select>
                                 </td>
                                 -->
                                  <td width="100%" colspan="2">
                                      <fieldset>
                                        <label class="block clearfix">                                      
                                          <span class="block input-icon input-icon-right">
                                          <input type="text" class="form-control newstyletxtinput"  autofocus="autofocus"  style="color:black!important" disabled="true" value="<?=$this->user->getUsername()?>" name="username_view" placeholder="Username" />
                                          <i class="ace-icon fa fa-user blue"></i>
                                          </span>
                                      </label>
                                          <input type="hidden"  value="<?=$this->user->getUsername()?>" name="username"  />                                            
                                      </fieldset>
                                      </td>
                                </tr>

                              <?php if(! $this->user_token ):?>
                                <tr>
                                  <td colspan="2" >
                                      <fieldset>
                                        <label class="block clearfix">                                      
                                          <span class="block input-icon input-icon-right">
                                          <input type="password" class="form-control newstyletxtinput" name="userpassword" placeholder="Current Password" />
                                          <i class="ace-icon fa fa-lock red"></i>
                                          </span>
                                      </label>
                                      </fieldset>
                                  </td>
                                </tr>
                              <?php else: ?>
                                  <input type="hidden" name="user_token" value="<?=$this->user_token?>" />                              
                             <?php endif ?> 
                               
                                <tr>

                                  <td colspan="2" >
                                      <fieldset>
                                        <label class="block clearfix">                                      
                                          <span class="block input-icon input-icon-right">
                                          <input type="password" class="form-control newstyletxtinput" name="newpassword" placeholder="New Password" />
                                          <i class="ace-icon fa fa-key red"></i>
                                          </span>
                                      </label>
                                      </fieldset>
                                  </td>

                                </tr>
                                <tr>

                                  <td colspan="2" >
                                      <fieldset>
                                        <label class="block clearfix">                                      
                                          <span class="block input-icon input-icon-right">
                                          <input type="password" class="form-control newstyletxtinput" name="confirmpassword" placeholder="Confirm" />
                                          <i class="ace-icon fa fa-check-circle red"></i>
                                          </span>
                                      </label>
                                      </fieldset>
                                  </td>

                                </tr>

                                <tr>

                                  <td colspan="2" >
                                      <fieldset>
                                        <label class="block clearfix">                                      
                                          <span class="block input-icon input-icon-right">
                                          <input type="password" class="form-control newstyletxtinput" name="member_code" placeholder="Member Code" />
                                          <i class="ace-icon fa fa-lock red"></i>
                                          </span>
                                      </label>
                                      </fieldset>
                                  </td>

                                </tr>

                                <!--
                                <tr>
                                  <td ><font color="black"><p  id=passwdlbl class="newstyletxt">Pin:</p></font></td>
                                  <td ><input name="pin" type="password" class="newstyletxtinput" id="pin"></td>
                                </tr>
                                -->
                                <tr>
                                  <td ></td>
                                  <td align="left">
                                    <input type="hidden" name="user_action" value="change"/>
                                    
                                    <input type="submit" name="Submit" value="Update" class="btn btn-primary btn-sm newstylebutton" onclick="return submit_onclick()">
                                    &nbsp;<a class="btn btn-yellow btn-sm newstylebutton" style="width:180px; " href="<?=$this->url('reset-password')?>"> Forgot Password?</a>                                  </td>
                                </tr>
                              </table>
                                </form>
