
<?php
    
    $redirect_parts=explode('?',urldecode($this->target));
    $base_part=$redirect_parts[0];
    $query_part='?'.(count($redirect_parts)>1?$redirect_parts[1]:'');

    if($base_part==''){
        $base_part='home/members';
    }
?>
                              <form action="<?=$this->url('reset-password')?>" method="post">

                                <h3 class="title blue">Reset Password </h3>

                              <table width="275" border="0">
                                <tr>
                                  <td width="94%" colspan="2">
                                      <fieldset>
                                        <label class="block clearfix">                                      
                                          <span class="block input-icon input-icon-right">
                                          <input type="text" class="form-control newstyletxtinput" autofocus="autofocus" name="username" placeholder="Username" value="<?=key_exists('username', $this->data)?$this->data['username']:''?>" />
                                          <i class="ace-icon fa fa-user red"></i>
                                          </span>
                                      </label>
                                      </fieldset>
                                      </td>
                                </tr>
                                <tr>
                                  <td width="94%" colspan="2">
                                      <fieldset>
                                        <label class="block clearfix">                                      
                                          <span class="block input-icon input-icon-right">
                                          <input type="text" class="form-control newstyletxtinput" name="email" placeholder="Email linked to account"  value="<?=key_exists('email', $this->data)?$this->data['email']:''?>" />
                                          <i class="ace-icon fa fa-envelope red"></i>
                                          </span>
                                      </label>
                                      </fieldset>
                                      </td>
                                </tr>
                                <tr>
                                  <td colspan="2" >
                                      <fieldset>
                                        <label class="block clearfix">                                      
                                          <span class="block input-icon input-icon-right">
                                          <input type="password" class="form-control newstyletxtinput" name="member_code" placeholder="Member Code"  value="<?=key_exists('member_code', $this->data)?$this->data['member_code']:''?>"  />
                                          <i class="ace-icon fa fa-lock red"></i>
                                          </span>
                                      </label>
                                      </fieldset>
                                  </td>
                                </tr>
                                <tr>
                                  <td ></td>
                                  <td align=left>
                                    <input type="hidden" name="target" value="<?=(isset($this->target))?$this->url($base_part).$query_part:''?>"/>
                                    <input type="submit" name="Submit" value="Submit" class="newstylebutton btn btn-sm btn-primary" ></input>
                                    <a  class="btn  btn-white btn-sm newstylebutton" style="color:#3a87ad!important;width:100px!important"href="<?=$this->url('auth/login')?>">
                                        <i class="ace-icon fa fa-key"></i>
                                        Back 
                                    </a>    
                                  </td>
                                </tr>
                              </table>
                            </form>
