<?php
// 
    // $this->headLink()->appendStylesheet('assets/projekktor/themes/maccaco/style.css',
                                         // 'screen',
                                         // true,
                                         // array()
                                       // );
                                       
    $this->headScript()->appendFile('/assets/projekktor/projekktor.min.js');

?>


<!-- ajax layout which only needs content area -->
<div class="page-header">
    <h1 style="">
        Help and Frequently Asked Questions - FAQ        
    </h1>
</div><!-- /.page-header -->

<div class="row">
    <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->
        <div class="tabbable">
            <!-- #section:pages/faq -->
            <ul class="nav nav-tabs padding-18 tab-size-bigger" id="myTab">
                <li class="active">
                    <a data-toggle="tab" href="#faq-tab-1">
                        <i class="blue ace-icon fa fa-comments  bigger-120"></i>
                        FAQ
                    </a>
                </li>

                <li>
                    <a data-toggle="tab" href="#userGuide">
                        <i class="green ace-icon fa fa-book bigger-120"></i>
                        User Guide
                    </a>
                </li>

                <li>
                    <a data-toggle="tab" href="#helpVideo">
                        <i class="orange ace-icon fa fa-film bigger-120"></i>
                        Video Tutorials
                    </a>
                </li>
                <!--
                <li>
                    <a data-toggle="tab" href="#faq-tab-4">
                        <i class="orange ace-icon fa fa-envelope-o bigger-120"></i>
                        Messages
                    </a>
                </li>
				-->
            </ul>

            <div class="tab-content no-border no-padding">
                <div id="faq-tab-1" class="tab-pane fade in active">
                    <h4 class="blue">
                        <i class="ace-icon fa fa-check bigger-110"></i>
                        General Questions
                    </h4>

                    <div class="space-8"></div>

                    <div id="faq-list-1" class="panel-group accordion-style1 accordion-style2">
                                                
                        
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <a href="#faq-1-1" data-parent="#faq-list-1" data-toggle="collapse" class="accordion-toggle collapsed">
                                    <i class="ace-icon fa fa-chevron-left pull-right" data-icon-hide="ace-icon fa fa-chevron-down" data-icon-show="ace-icon fa fa-chevron-left"></i>

                                    <i class="ace-icon fa fa-key bigger-130"></i>
                                    &nbsp; Why does it not let me keep a short password?
                                </a>
                            </div>

                            <div class="panel-collapse collapse" id="faq-1-1">
                                <div class="panel-body">
                                    There is confidential information entered here. It also is a portal for document distribution and messages amongst office bearers. Therefore the security of the site is important. Keeping weak passwords is not an acceptable. In fact you should also ensure that all your passwords are sufficiently strong so that they cannot be easily compromised. 
                                    
                                </div>
                            </div>
                        </div>
                        
                        
                        
                    <div class="panel panel-default">
                            <div class="panel-heading">
                                <a href="#faq-1-2" data-parent="#faq-list-1" data-toggle="collapse" class="accordion-toggle collapsed">
                                    <i class="ace-icon fa fa-chevron-left pull-right" data-icon-hide="ace-icon fa fa-chevron-down" data-icon-show="ace-icon fa fa-chevron-left"></i>

                                    <i class="ace-icon fa fa-lock bigger-130"></i>
                                    &nbsp; 
                                        Why does my account become inactive when a change is made to the profile? 
                                </a>
                            </div>

                            <div class="panel-collapse collapse" id="faq-1-2">
                                <div class="panel-body">

                                    An account is created at the time of the approval. Therefore any change that is made to the account needs to be made with approval of Markaz. Things like adjusting the password or contact number can be done by the user, however, other things when modified by the General Secretary of the Branch or Sadr will result in the account being locked. Once these changes are accepted by Markaz, the account will become active. 
                                    
                                </div>
                            </div>
                        </div>                        
                    <div class="panel panel-default">
                            <div class="panel-heading">
                                <a href="#faq-1-3" data-parent="#faq-list-1" data-toggle="collapse" class="accordion-toggle collapsed">
                                    <i class="ace-icon fa fa-chevron-left pull-right" data-icon-hide="ace-icon fa fa-chevron-down" data-icon-show="ace-icon fa fa-chevron-left"></i>

                                    <i class="ace-icon fa fa-search bigger-130"></i>
                                    &nbsp; 

                                        Can I get contact information about my counter parts?

                                </a>
                            </div>

                            <div class="panel-collapse collapse" id="faq-1-3">
                                <div class="panel-body">

                                    Yes. You click on Office Bearers and then on the top right hand corner you have a selection of lists that you can view. Depending on your reporting level, you will be shown the information for your counter parts. 
                                    
                                </div>
                            </div>
                        </div>                        
                    <div class="panel panel-default">
                            <div class="panel-heading">
                                <a href="#faq-1-4" data-parent="#faq-list-1" data-toggle="collapse" class="accordion-toggle collapsed">
                                    <i class="ace-icon fa fa-chevron-left pull-right" data-icon-hide="ace-icon fa fa-chevron-down" data-icon-show="ace-icon fa fa-chevron-left"></i>

                                    <i class="ace-icon fa fa-newspaper-o bigger-130"></i>
                                    &nbsp; 

                                    I have more than one Department. How do I enter my report for the other Department?

                                </a>
                            </div>

                            <div class="panel-collapse collapse" id="faq-1-4">
                                <div class="panel-body">

                                    When you are creating a report, it will give you the option of all the departments that you are responsible for. Create the monthly report for each one of your departments by going to Reports and pressing the Create button and choosing your Department from the drop down menu. 
                                    
                                </div>
                            </div>
                        </div>                        
                    <div class="panel panel-default">
                            <div class="panel-heading">
                                <a href="#faq-1-5" data-parent="#faq-list-1" data-toggle="collapse" class="accordion-toggle collapsed">
                                    <i class="ace-icon fa fa-chevron-left pull-right" data-icon-hide="ace-icon fa fa-chevron-down" data-icon-show="ace-icon fa fa-chevron-left"></i>


                                    <i class="ace-icon fa fa-bank bigger-130"></i>
                                    &nbsp; 

                                    Why can I not directly submit my report to Markaz? 
                                </a>
                            </div>

                            <div class="panel-collapse collapse" id="faq-1-5">
                                <div class="panel-body">

                                    As a Secretary, your report must be verified by the Local Amir/Sadr of your Jama`at. Without this verification the report cannot be submitted to Markaz. This ensures that the Local Amir/Sadr Jama`at are aware of what is being reported to Markaz as they are answerable to Markaz for all activities that happen in their Jama`at. 
                                    
                                </div>
                            </div>
                        </div>  
                        

                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <a href="#faq-1-6" data-parent="#faq-list-1" data-toggle="collapse" class="accordion-toggle collapsed">
                                    <i class="ace-icon fa fa-chevron-left pull-right" data-icon-hide="ace-icon fa fa-chevron-down" data-icon-show="ace-icon fa fa-chevron-left"></i>


                                    <i class="ace-icon fa fa-bank bigger-130"></i>
                                    &nbsp; 
                                    
                                    Why doe the Halqa report not go to Markaz?
                                </a>
                            </div>

                            <div class="panel-collapse collapse" id="faq-1-6">
                                <div class="panel-body">

                                    Jama`ats report directly to Markaz. When a Jama`at is subdivided into Halaqajat it is called an Imarat and is headed by a local Amir who has his full `Amila as well. The Sadran Halqa and Secretary Halqa reports directly to their counterparts at the Jama`at (Imarat) level. Therefore, the monthly report of Halqa Secretaries are received by the Secretary at the Jama`at level. They are responsible for providing the feedback to the Halqa Secretaries. 
                                    
                                </div>
                            </div>
                        </div>                           
                                              
                    <div class="panel panel-default">
                            <div class="panel-heading">
                                <a href="#faq-1-7" data-parent="#faq-list-1" data-toggle="collapse" class="accordion-toggle collapsed">
                                    <i class="ace-icon fa fa-chevron-left pull-right" data-icon-hide="ace-icon fa fa-chevron-down" data-icon-show="ace-icon fa fa-chevron-left"></i>

                                    <i class="ace-icon fa fa-comments-o bigger-130"></i>
                                    &nbsp; 

                                        Does someone look at my report? How do I know that my report has been reviewed? 

                                </a>
                            </div>

                            <div class="panel-collapse collapse" id="faq-1-7">
                                <div class="panel-body">

                                        Your report are looked at by your counterpart in the National/Jama`at level. Once they are reviewed your report, they can optionally provide you with feedback for your report as well. When they have completed their review and received your report, an email alert will be sent to you so you can review the information. 
                                    
                                </div>
                            </div>
                        </div>                        
                        
                        
                    <div class="panel panel-default">
                            <div class="panel-heading">
                                <a href="#faq-1-8" data-parent="#faq-list-1" data-toggle="collapse" class="accordion-toggle collapsed">
                                    <i class="ace-icon fa fa-chevron-left pull-right" data-icon-hide="ace-icon fa fa-chevron-down" data-icon-show="ace-icon fa fa-chevron-left"></i>

                                    <i class="ace-icon fa fa-mobile-phone bigger-130"></i>
                                    &nbsp; 

                                    How do I access the report on my mobile device? 

                                </a>
                            </div>

                            <div class="panel-collapse collapse" id="faq-1-8">
                                <div class="panel-body">

                                    The current reporting system is mobile friendly. You have to do nothing different on the mobile device or tablet. Simply access the reporting site through your mobile browser and it will adjust to the screen appropriately. 
                                    
                                </div>
                            </div>
                        </div>                        
                        
                        
                        
                        
                    </div>            
            </div>
            
            <div id="userGuide" class="tab-pane fade in no-margin no-padding ">
                
                    <div class="widget-box ui-sortable-handle">
                        <div class="widget-header widget-header-small">
                            <h5 class="widget-title smaller">User Guide V 2.0</h5>

                            <!-- #section:custom/widget-box.tabbed -->
                            <div class="widget-toolbar no-border left ">
                                <ul class="nav nav-tabs  tabs-left" id="myTabGuide">
                                    <li class="active">
                                        <a data-toggle="tab" href="#intro" aria-expanded="true">Introduction</a>
                                    </li>

                                    <li class="">
                                        <a data-toggle="tab" href="#access" aria-expanded="false">Access & Navigation</a>
                                    </li>
                                    <li class="">
                                        <a data-toggle="tab" href="#password" aria-expanded="false">Password Changes</a>
                                    </li>

                                    <li class="">
                                        <a data-toggle="tab" href="#reports" aria-expanded="false">Report Submission</a>
                                    </li>
                                    <li class="">
                                        <a data-toggle="tab" href="#users" aria-expanded="false">Branch Users</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="widget-toolbar no-border left ">
                                <a class="btn btn-default btn-sm btn-round  btn-warning btn-white" href="<?=$this->basePath()?>/UserGuide/AMJ Reports User Guide 2015 v.2.0.pdf">&nbsp;Download&nbsp;</a>
                            </div>

                            <!-- /section:custom/widget-box.tabbed -->
                        </div>

                        <div class="widget-body">
                            <div class="widget-main padding-6">
                                <div class="tab-content">
                                    <div id="intro" class="tab-pane active">
                                        <?php include ROOT_PATH.'/public/UserGuide/html/Introduction.html'; ?>
                                    </div>

                                    <div id="access" class="tab-pane">
                                        <?php include ROOT_PATH.'/public/UserGuide/html/Access and Navigation.html'; ?>
                                    </div>

                                    <div id="password" class="tab-pane">
                                        <?php include ROOT_PATH.'/public/UserGuide/html/Password.html'; ?>
                                    </div>

                                    <div id="reports" class="tab-pane">
                                        <?php include ROOT_PATH.'/public/UserGuide/html/Report Submission Process.html'; ?>
                                    </div>
                                    <div id="users" class="tab-pane">
                                        <?php include ROOT_PATH.'/public/UserGuide/html/Branch Users.html'; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>
            

        	</div>
            
            <div id="helpVideo" class="tab-pane fade in no-padding">
                <div class="space-10 col-sm-12"></div>
                
            	<div class=" col-sm-12  no-padding">
            	    
                    <div class="col-sm-6 padding-lg-bottom">            	    
                		<video class="projekktor"  
                		   width="480"
                		   poster="<?=$this->basePath()?>/UserGuide/homescreen.png" controls="yes">
                              <source src="<?=$this->basePath()?>/UserGuide/Homepage.mp4" />                          
                             <p class="vjs-no-js">
                                  To view this video please enable JavaScript, and consider upgrading to a web browser that
                                  <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
                                </p>
                        </video>
                   </div>


                    <div class="col-sm-6  padding-lg-bottom">                  
                     
                        <video class="projekktor"  
                           width="480"
                           poster="<?=$this->basePath()?>/UserGuide/menubuttons.png" controls="yes">
                              <source src="<?=$this->basePath()?>/UserGuide/MenuButtons.mp4" />                          
                             <p class="vjs-no-js">
                                  To view this video please enable JavaScript, and consider upgrading to a web browser that
                                  <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
                                </p>
                        </video>
                    </div>

                    <div class="col-sm-6 padding-lg-bottom">                    
                        <video class="projekktor"  
                           width="480"
                           poster="<?=$this->basePath()?>/UserGuide/poster.png" controls="yes">
                              <source src="<?=$this->basePath()?>/UserGuide/CP_vid2.mp4" />                          
                              <source src="<?=$this->basePath()?>/UserGuide/CP_vid2.ogv" />
                             <p class="vjs-no-js">
                                  To view this video please enable JavaScript, and consider upgrading to a web browser that
                                  <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
                                </p>
                        </video>
                   </div>
                     
            	</div><!-- videos-->
        	</div>

            </div>
    </div><!-- tabable -->
   </div><!-- col-sm-12-->
</div><!-- row -->   
<script>
    <!--
    $(function(){
        
        // cache the id
        var navbox = $('#myTab, #myTabGuide');
        // activate tab on click
        navbox.on('click', 'a', function (e) {
          var $this = $(this);
          // prevent the Default behavior
          e.preventDefault();
          // set the hash to the address bar
          window.location.hash = $this.attr('href');
          // activate the clicked tab
          $this.tab('show');
        })
        
        // if we have a hash in the address bar
        if(window.location.hash){
          // show right tab on load (read hash from address bar)
          navbox.find('a[href="'+window.location.hash+'"]').tab('show');
        }
        
        // projekktor('video', {
        // volume: 0.8,
        // autoplay: false,
        // addplugins: ['controlbar'],
        // controls:true,
        // playerFlashMP4: '<?=$this->basePath()?>/assets/projekktor/swf/StrobeMediaPlayback.swf',
        // playerFlashMP3: '<?=$this->basePath()?>/assets/projekktor/swf/StrobeMediaPlayback.swf'
        // });


        //enlarge video that is being user just started and pause all other videos
        $('video').on('play',function(){
            $this=$(this);
            var video_playing=this;
            $('video').not(this).each(function(){
                var video = this;
                video.pause();
                $(video).attr('width','480')
                .parent('div').removeClass('col-sm-12').addClass('col-sm-6')
            });
            
            $this.parent('div').removeClass('col-sm-6').addClass('col-sm-12')
            $this.attr('width','1024');
        
        });
            
    });
    -->
</script>