<?php 
$height=$this->height?$this->height:300;
$office = $this->office;
$data = $this->dashboard_data;

$data_last=$data['samebranch']['status_last'];
$last_total=count($data['samebranch']['last']);

if($last_total>0){
    $last_outstanding=$data_last['outstanding']['y'];
    $last_outstanding_perc=round($last_outstanding/$last_total*100,0);    

    $last_completed=isset($data_last['completed'])?$data_last['completed']['y']:0;
    $last_completed_perc=round($last_completed/$last_total*100,0);    
}

$data_ytd=(array_values($data['samebranch']['status_ytd']));

$index=-1;
foreach ($data_ytd as $key => $value) {
	if($value['name']=='Outstanding'){
	    $index=$key;
	}
}
unset($data_ytd[$index]);

//print_r(array('<!-- data_ytd_print',$data_ytd,'-->'));

$data_ytd=(array_values($data_ytd));
?>

    <div class="col-sm-12 infobox-container2">
        <h3 class="title align-center">Report Submissions for <?=$office->getBranch()->getBranchName()?>, all Departments </h3 >
    </div>
    <div class="col-sm-5 infobox-container2">
            <!-- #section:pages/dashboard.infobox -->
            <div class="col-sm-12 infobox-container2">
                <h4 class="title">Reports for <?=$data['period_code']?></h4>
            </div>
            <div class="infobox infobox-red">
                <div class="infobox-data-number bolder">Outstanding Reports</div>
                <div class="infobox-progress">
                    <!-- #section:pages/dashboard.infobox.easypiechart -->
                    <div class="easy-pie-chart percentage" data-percent="<?=$last_outstanding_perc?>" data-size="80">
                        <span class="percent"><?=$last_outstanding?></span>
                    </div>
                    <!-- /section:pages/dashboard.infobox.easypiechart -->
                </div>
            </div>
    
            <div class="infobox infobox-orange">
                <div class="infobox-data-number bolder">Completed Reports </div>
                <div class="infobox-progress">
                    <!-- #section:pages/dashboard.infobox.easypiechart -->
                    <div class="easy-pie-chart percentage" data-percent="<?=$last_completed_perc?>" data-size="80">
                        <span class="percent"><?=$last_completed?></span>
                    </div>
    
                    <!-- /section:pages/dashboard.infobox.easypiechart -->
                </div>    
            </div>
    
    </div>
    
    
    <div class="no-margin no-padding col-sm-5 chartWrap" >
        <h4 class="title align-center">Year-to-Date reports</h4>
        <div id="samebranch_reports_chart" style="height: 300px"></div>
    </div>            

<?php

//print_r(json_encode($data_ytd));

?>    
<script >

$(function () {
    
    
        //Trafic and Task radial pie
        $('.easy-pie-chart.percentage').each(function(){
            var $box = $(this).closest('.infobox');
            var barColor = $(this).data('color') || (!$box.hasClass('infobox-dark') ? $box.css('color') : 'rgba(255,255,255,0.95)');
            var trackColor = barColor == 'rgba(255,255,255,0.95)' ? 'rgba(255,255,255,0.25)' : '#E2E2E2';
            var size = parseInt($(this).data('size')) || 50;
            $(this).easyPieChart({
                barColor: barColor,
                trackColor: trackColor,
                scaleColor: false,
                lineCap: 'butt',
                size:'175',
                lineWidth: parseInt(size/10),
                animate: /msie\s*(8|7|6)/.test(navigator.userAgent.toLowerCase()) ? false : 1000,
                size: size
            });
        });        

         
        $('.infobox').height('100px').css('padding-right','15px');
    
    
    //High Cahrt PIE for Reports
    $('#samebranch_reports_chart').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false
        },
        title: {
            text: '',
            align:'right',
        },
        credits:false,
        tooltip: {
            //enabled:false,
            pointFormat: '{series.name}: <b>{point.y}</b>'
        },
        legend : { 
            useHTML:false ,
            borderColor: 'silver',
            enabled: true,
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.y}',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                }
            }
        },
        colors:['#333333','#FEE188','#3A87AD','#82AF6F','#CC3300','#CCCCCC'],
        series: [{
            type: 'pie',
            name: 'Reports ',
            data:<?=json_encode($data_ytd)?>,
            // [
//                     
                     // {name:'Draft',y:1,sliced: false,},
                     // {name:'Completed',y:2,sliced: false,},
                     // {name:'Verified',y:1,sliced: false,},
                     // {name:'Received',y:3,sliced: false,},
                     // {name:'Outstanding',y:3,sliced: true,},
//                      
                // ]
        }]
    });
     
});

</script>

