<?php 

$height=$this->height?$this->height:300;
$subordinate_total=count($this->dashboard_data['subordinate']['last']);

?>


    <div class="col-sm-12 infobox-container2">
        <h3 class="title align-center">Monthly Reports for All <?=$this->subordinate_title?></h3 >
    </div>
    
    <div class="col-sm-12">
        <div id="monthly_subbranches"></div>
    </div>

<script >

$(function () {
   
    //Highchart Bar Chart 
     // HichCharts verticle bar chart
<?php
//print_r(array("<<<",$this->subordinate_graph_data,">>>"));
//exit;
?>     
      var report_data = <?=json_encode($this->subordinate_graph_data)?>;
     
       $('#monthly_subbranches').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: '',//'Monthly Reports for All <?=$this->subordinate_title?>',
            //verticalAlign:'bottom',
            style:{
                //'margin-top':'30px'
            }
        },
        
        // subtitle: {
            // text: 'Source: WorldClimate.com'
        // },
        xAxis: {
            categories: report_data['categories'],// [ 'Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
            crosshair: false
        },
        series: report_data['series'] ,
        yAxis: {
            min: 0,
            max:<?=$subordinate_total?>,
            title: {
                text: '<?=$this->subordinate_title?>'
            },
            stackLabels: {
                enabled: false,
                style: {
                    fontWeight: 'bold',
                    color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
                }
            }
        },
        credits:false,
        tooltip: {
            //headerFormat: '<span style="font-weight:bolder">{point.key}</span>',
            pointFormat: '<table><tr><td style="padding:4px">{series.name}: </td>' +
                '<td style="width:10px;display:block;background-color:{series.color};padding:4px;"> </td>'+
                '<td style="padding:3px"><b>{point.y}</b></td></tr></table>',
                //'<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
            footerFormat: '</table>',
            shared: false,
            //useHTML: true,
            backgroundColor: '#FCFFC5',
            style:{'z-index':9000,'opacity':1}
        },
        plotOptions: {
            column: {
                stacking: 'normal',
                dataLabels: {
                    enabled: false,//true,
                    color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white',
                    style: {
                        textShadow: '0 0 3px black'
                    }
                },
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
         legend : { 
            useHTML:false ,
            borderColor: 'silver',
            enabled: true,
            //layout: 'vertical',
            align: 'center',
            //verticalAlign: 'top',
            itemWidth:200,
            //floating:true,
            style:{
              'margin-top':'100px',
            },
            itemStyle: {
              'z-index':'0',
              //width:'100%'
            }
          }
        
    });        
});

</script>

