<style>
    
.modal-dialog{
    width:500px!important;
}

</style>

<div class="widget-container-col col-sm-12 no-padding no-margin" style="float: none">

<!--
<div class="widget-header widget-header-blue">
   
    <h3 class=" widget-title inline">
        Office Bearers List for <?php echo $this->zfcUserIdentity()->getDisplayName() ?>
    </h3>   

    <div class="widget-toolbar">        
        
       <button  id="create"  value="create" class="align-right btn btn-sm btn-primary btn-round">Change Request</button>       
    </div>

</div>
-->
<?php echo $this->requests_grid; ?>


</div>


<div class="space-10"></div>
