<?php include __DIR__.'/../../partial/grid_includes.phtml' ?>

<?php
    $this->headLink()
        ->appendStylesheet($this->basePath() . '/assets/css/select2.css');
  
    $this->headScript()->appendFile( $this->basePath() . '/assets/js/select2.min.js','text/javascript',array());
    $this->headScript()->appendFile( $this->basePath() . '/js/custom.select2.js','text/javascript',array());

?>
<h1>
    
</h1>

<form name="update_request" id="update_request" action="/office-assignment/request" method="post">
    <input type="hidden" name="request_id" id="request_id_to_edit"  />
    <input type="hidden" name="request_action" value="edit"/>
</form>
<table id="requests_grid"></table>
<div id="requests_pager"></div>

<script>
    function submitForm(target){
//        alert('submitForm');
//        var row=CommonDataGrid.getRowDataFromClick(target);
        document.location.href='/office-assignment/request?request_id='+row['id'];
    };

$(document).ready(function(){
    
    
    var actionsFunction=function ( cellvalue, options, rowObject ){
//        setTimeout(function(){console.log($('#requests_grid .ui-inline-edit').length)},1000);
        var clickCode="$('#update_request > #request_id_to_edit').val('"+rowObject['id']+"');$('#update_request').submit();";
        return '<div title="Edit selected row" id="jEditButton_'+rowObject['id']+'"  onclick="'+clickCode+'" style="float:left;cursor:pointer;" class="ui-pg-div ui-inline-edit"  onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\')"><span class="ui-icon ace-icon fa fa-edit bigger-140"></span></div>';
    };
                                
    SimpleDataGrid.create({'grid_selector':'#requests_grid','pager_selector':'#requests_pager',
                         'url':'<?php echo $this->url("office-assignment/requests") ?>/json',
                         'editurl': '<?php echo $this->url("office-assignment/requests") ?>/json', //"/dummy.html",//nothing is saved
                          'gridTitle':'<?php echo $this->translate('Office Assignment Requests')?>',
                          'dataRoot':'data',
                          'editable':false,
                          'colModel':[
                            {index:'id',name:'id',label:'Id',sorttype:"int",hidden:true},
                            {index:'member_code',name:'member_code',label:'Membercode',editable:true,edittype:"text"},
                            {index:'full_name',name:'full_name',label:'Name',editable:true,edittype:"text"},
                            {index:'email',name:'email',label:'Email',editable:true,edittype:"text",hidden:true},
                            {index:'phone_primary',name:'phone_primary',label:'Phone',editable:true, viewable: true,edittype:"text",hidden:true,editrules:{edithidden:true}},
                            {index:'phone_alt',name:'phone_alt',label:'Phone Alt.',editable:true, viewable: true,edittype:"text",hidden:true,editrules:{edithidden:true}},

                            {index:'branch.branch_name',name:'branch.branch_name',label:'Branch',editable:true,edittype:"text"
                                ,editoptions:{
                                            dataInit:function(element){                                                
                                                        setTimeout(function(){
                                                            CustomSelect2.createSimple({
                                                                placeholder:'Select Department',
                                                                url:'<?php echo $this->url("config/branch")?>/json',
                                                                id:'id',
                                                                label:'branch_name',
                                                                element:$(element),
                                                                data_target:'data',
                                                                initValLabel:true
                                                            })                
                                                        }                                            
                                                        ,50);                                                
                                                }
                                            },

                            },
                            
                            {index:'department.department_name',name:'department.department_name',label:'Department',editable:true,edittype:"text"
                                ,editoptions:{
                                            dataInit:function(element){                                                
                                                        setTimeout(function(){
                                                            CustomSelect2.createSimple({
                                                                placeholder:'Select Department',
                                                                url:'<?php echo $this->url("config/department-json")?>',
                                                                id:'id',
                                                                label:'department_name',
                                                                element:$(element),
                                                                data_target:'data',
                                                                initValLabel:true
                                                            })                
                                                        }                                            
                                                        ,50);                                                
                                                }
                                            },
                            },
                            {index:'status',name:'status',label:'Status',editable:true,
                                edittype:"select",editoptions:{value:<?=$this->office_assignment_req_status?>}
                                }
                           ,{
                            name: 'actions',
                            index: 'actions',
                            width: 30,
                            editable: false,
                            search:false,
                            label:' ',
                            formatter:actionsFunction
                        }
                          ]
                          });
                          
        
        

});    
</script>