<?php
    $col = $this->col; 
    $value=$col->getFilterActiveValue();
    $value = preg_replace('/\~ \*(.*)\*/','\1',$value);
    $value = preg_replace('/\= (.*)/','\1',$value);
  
    $name = sprintf("toolbarFilters[%s]",$col->getUniqueId());
    $id = sprintf("input_%s",$col->getUniqueId());
     
    if(isset($form)){
        $form->add(array(
                 'type' => 'Zend\Form\Element\Select',
                 'name' => $name,
                 'options' => array(
                         'label' => 'Month',
                         'value_options' => $form->getOption('branches'),
                         'empty_option' => 'All',                     
                 ), 
                'attributes' => array(
                         'value'=>$value,
                         'id'=>$id,
                         'class'=>'select2',
                         'style'=>'width:175px'
                    )                       
        ));

        
        echo $this->formSelect($form->get($name));
                
    }  
?>
 
<script>
    $(function(){
        
        $('#<?=$id?>').select2({
            minimumResultsForSearch: 10
        });

        $('#<?=$id?>').change(function(){
            document.forms["form_<?=$this->gridId?>"].submit();
        });
                     
    });
    
</script> 
